### ISSUE TITLE
IOS Client packet size above MTU not work

### ISSUE THREAD

**Issue by stramanu** [OpenVPN/openvpn3#10]
Hi, I implemented this source code for an ios client.
When I try to send, from another client, a packet (ping xx.xx.xx.xx -c 1 -s 1400) sized 1400 bytes or higher, it isn't forwarded and I saw this log on the ios client:
`LZO-ASYM uncompress 327 -> 1428`

Have you any idea of what is going on?

**Comment by ChineseRoyalStar** [comment]
You are great. How do you implement this source code for iOS? Can you provide any Demo or steps? Thank you.

**Comment by schwabe** [comment]
There is no general problem known of sending large packets in iOS. And this bug is now quite old, so I am closing it for now.  If the problem still exists, please respond with more detailed information.
