### ISSUE TITLE
OpenVPN connect v3 certificate only accept pkcs12 certs

### ISSUE THREAD

**Issue by nerokiryu** [OpenVPN/openvpn3#100]
version openVPN connect : 3.1.1 (378) beta

On windows 10 when you try to use the latest version of openvpn connect and you want to add your certificate on the gui you can only add a pkcs12 cert (by the extention of the file).
I need .crt certificate to access my vpn server.
Can it be added as a feature on the gui or is there a way to go around this problem without rebuilding my cert ( i do not have the key to generate it) ?

by the way the new interface is sleek.

Thanks !

**Comment by KreativJos** [comment]
Currently I have the same issue. I have tried adding the certificate via the config file, but I cannot seem to find the certificate in the selection list when added in the config.

**Comment by schwabe** [comment]
This should be reported to the UI app via https://openvpn.net/contact/. This repository is only for the openvpn3 library.
