### ISSUE TITLE
Public Key not found for Debian 10 (Buster)

### ISSUE THREAD

**Issue by aaronjohnsabu1999** [OpenVPN/openvpn3#113]
`...
    Err:8 https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease  
    The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 551180AB92C319F8  
    ...
    Reading package lists... Done                                   
    W: GPG error: https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 551180AB92C319F8  
    E: The repository 'https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease' is not signed.  
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.  
    N: See apt-secure(8) manpage for repository creation and user configuration details.  
`

Please suggest how to solve this issue. I have installed `apt-transport-https`, so it is not an issue of that not being there on the system.

**Comment by dsommers** [comment]
First of all, this is not an openvpn3 project issue, but more related to the openvpn3-linux project.  That aside, did you remember to install the repository keys as described here? https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux#DebianUbuntu

     # wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
     # apt-key add openvpn-repo-pkg-key.pub

If this is still an issue, file a request in this project: https://github.com/OpenVPN/openvpn3-linux

**Comment by aaronjohnsabu1999** [comment]
I'm not sure what you mean by that. Do you mean that the Linux implementation of OpenVPN3 is possibly faulty and not OpenVPN?

**Comment by dsommers** [comment]
No.  I mean you most likely have not performed the `wget` and `apt-key` steps as indicated in my previous reply.  Which is why `apt install` complains about a missing public key.
