### ISSUE TITLE
Message loop for ovpnagent

### ISSUE THREAD

**Issue by ali-reza-zareian** [OpenVPN/openvpn3#116]
Hi
How can I add a message loop to the Win::Service class?

I need a windows messages loop to handle USB device notification. I want to stop ovpnagent service if the USB HID device is detached.

**Comment by schwabe** [comment]
We use asio for all asynchronous i/o. See asio documentation how to do that. The ASIO io context is readily available as io_context in the class.

As side note if you want to implement something like disconnecting when a smartcard/yubikey is removed, this does not belong into the ovpnagent but rather in the normal client.
