### ISSUE TITLE
Add the logo in organization

### ISSUE THREAD

**Issue by Neustradamus** [OpenVPN/openvpn3#119]
Can you add the logo in this OpenVPN organization?
- https://github.com/openvpn

**Comment by dsommers** [comment]
Not applicable for the OpenVPN 3 project.

**Comment by mattock** [comment]
Having the PenVPN logo in the GitHub organization still makes sense imho :smile:.

**Comment by theAkito** [comment]
@dsommers What? 🤔

**Comment by dsommers** [comment]
This is the issue tracker of the OpenVPN 3 Core library.  That's all.  Not an issue tracker for how the OpenVPN organization is configured.

**Comment by theAkito** [comment]
@dsommers So if that's the case, where is your reference to the organisational issue tracker?

That said, you could still take note of this, even if it is not the perfect place and the issue can be closed, I mean you are not an API that misunderstands the request.

**Comment by Neustradamus** [comment]
Thanks for your comments.

I have done the ticket here because there is not other place to request it, the icon is missing here:
- https://github.com/openvpn

**Comment by mattock** [comment]
Fixed.

**Comment by theAkito** [comment]
Humans are so versatile and powerful.

**Comment by Neustradamus** [comment]
@mattock: Thanks a lot!
This GitHub organization is now more beautiful, more serious, ...

Thanks all for your participation in this discussion :)
