### ISSUE TITLE
Is openvpn connect for android/ios open source?

### ISSUE THREAD

**Issue by charlessoft** [OpenVPN/openvpn3#120]
Is openvpn connect for android/ios open source?
where is the source address.

**Comment by dsommers** [comment]
OpenVPN 3 based products can be seen as 2 main components. 1) A backend which is the main VPN part, which handles all the network connection between local and remote ends, configuration of virtual network devices, IP addresses, routes, DNS, etc. And 2) the management layer which users interact with. This management is responsible to manage configuration profiles, starting/stopping VPN sessions and ensuring the VPN sessions handles various host events such as sleep and resume.

OpenVPN Connect uses this OpenVPN 3 project for 1), which is open source. The management layer is not open source.
