### ISSUE TITLE
Are there any ios/android openvpn3 demos for learning

### ISSUE THREAD

**Issue by charlessoft** [OpenVPN/openvpn3#121]
ios/android openvpn connect client isn't open source,
Are there any ios/android use openvpn3 demos for learning

**Comment by dsommers** [comment]
Have a look at the [ics-openvpn project](https://github.com/schwabe/ics-openvpn/), this is the open source "OpenVPN for Android" project, which incorporates both OpenVPN 2.x and the OpenVPN 3 Core library.

And also don't abuse the issue ticketing system for support questions like this.  Use one of the methods described here: https://community.openvpn.net/openvpn/wiki/GettingHelp#Developersupport
