### ISSUE TITLE
TUN Error: tun_builder_error: tun_builder_new failed

### ISSUE THREAD

**Issue by 82571701** [OpenVPN/openvpn3#123]
![image](https://user-images.githubusercontent.com/25925163/95543722-e19d8380-0a2b-11eb-9fcf-b2ee6689ebd0.png)
I created a class'myClient.cpp' inherited from ClientAPI::OpenVPNClient. After I set the user name, password, and certificate information, I called the connect () method, and then an error was reported..Did I use it wrong? 
![image](https://user-images.githubusercontent.com/25925163/95543994-920b8780-0a2c-11eb-8d2c-569966179365.png)

**Comment by schwabe** [comment]
Please use copying of code and code formatting and not screenshots. With the little details you have given, it is impossible to figure out what is wrong in your case. If you think there is a bug in our library or need a working example, please use the test client in https://github.com/OpenVPN/openvpn3/tree/master/test/ovpncli
