### ISSUE TITLE
how import profile via url?

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#124]
use mac openvpn connected client, import profile form url(https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/al18.nordvpn.com.tcp443.ovpn)

display error message:
![image](https://user-images.githubusercontent.com/72748373/95764273-cf00a400-0ce2-11eb-8542-93dd82d0ba9d.png)

if i import profile form "FILE" button, it works well.

**Comment by dsommers** [comment]
The "Import via URL" is intended to be used against OpenVPN Access Server and OpenVPN Cloud, or any other service using the same protocol.
