### ISSUE TITLE
missing jsoncppConfig problem?

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn3#128]
I am following the documentation to Build OpenVPN 3 on Windows, but when I try to run this line in git:
`cmake -DCMAKE_TOOLCHAIN_FILE=C:\Users\Bence\vcpkg\scripts\buildsystems\vcpkg.cmake -A x64 -B build openvpn3`
It fails to complete the configuration and gives me this error:

```
CMake Error at C:/Users/Bence/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_find_package):
  Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake/findcoredeps.cmake:139 (find_package)
  test/ovpncli/CMakeLists.txt:51 (add_json_library)
```
![image](https://user-images.githubusercontent.com/42838737/99242747-f4139580-27ff-11eb-8389-d592fb79118a.png)

What is the problem? What should I install?

**Comment by lstipakov** [comment]
I don't have Windows box next to me to check, but it looks like you might need to install jsoncpp with vcpkg:

`vcpkg install jsoncpp:x64-windows`
