### ISSUE TITLE
Build steps for Windows

### ISSUE THREAD

**Issue by vivekbhgn** [OpenVPN/openvpn3#13]
Can you please provide instructions for building OpenVPN client for windows too?

**Comment by Ahmedoaf** [comment]
You must help me to activate this is program

**Comment by lstipakov** [comment]
Hi @vivekbhgn,

Windows support has recently been improved and documented, see https://github.com/OpenVPN/openvpn3#building-the-openvpn-3-client-on-windows

Let me know if you have any questions!

**Comment by vivekbhgn** [comment]
@lstipakov Thanks a lot, it really helped.

**Comment by wll0117** [comment]
How to compile 32-bit
