### ISSUE TITLE
 Is openvpn3 the repository I am looking for?

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn3#132]
I want to make changes to the GUI of open vpn 3. Is this the right repo for it?
If so, how can I build the graphical interface from Visual Studio?
If this is not the repo, which one should I clone?
IMPORTANT: I am looking to make changes to the openvpn3 gui, not the simpler, classic open vpn 2.x, which has the openvpn-gui repo.

**Comment by schwabe** [comment]
The official OpenVPN Connect Client is not open source.
