### ISSUE TITLE
Windows OVPN Metric Issue

### ISSUE THREAD

**Issue by zer0pwned** [OpenVPN/openvpn3#133]
Hey,

Lately I updated my Windows OpenVPN Connect client from old version to 3.2.2(1455) and suddenly it cannot connect to my OpenVPN server anymore. So I did a bit of investigation and found out the new OpenVPN client picked the wrong gateway while I was using Zerotier. 

I looked into the openvpn log file and found the following log along with other useful information:
```
===========================================================================
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      10.227.X.1    10.227.X.X      4
          0.0.0.0          0.0.0.0   25.255.255.254    10.147.X.X  10034
# Zerotier connected prior to OpenVPN
Fri Nov 20 19:37:46 2020 GetBestGateway: selected gateway 25.255.255.254 on adapter 8 for destination 107.X.X.X
# Zerotier disconnected prior to OpenVPN
Fri Nov 20 19:55:21 2020 GetBestGateway: selected gateway 10.227.X.1 on adapter 9 for destination 107.X.X.X
```

As you can see, openvpn client picked up wrong gateway/interface. I have been using OpenVPN and Zerotier for a while and I never experienced such issue before this upgrade. I don't have source code of Windows OpenVPN connect but I assume it leverages the source code of openvpn3 as the functionality core so I searched the source code based on the log keyword. 

Two month ago, in commit d8e99cf5c133704df22c57bd7a6e6b4e8dc2598a, the following code was added into file `openvpn\tun\win\tunutil.hpp` to improve bypass route logic. 

```c
auto cur_prefix = IPv4::Addr::prefix_len_32(ntohl(gw->dwForwardMask));
auto new_prefix = IPv4::Addr::prefix_len_32(ntohl(row->dwForwardMask));
auto new_metric_is_higher = row->dwForwardMetric1 > gw->dwForwardMetric1;

if ((new_prefix > cur_prefix) || ((new_prefix == cur_prefix) && (new_metric_is_higher)))
    gw = row;
```

I didn't find how `dwForwardMetric1` was acquired and parsed. If this value was acquired from Windows and without any modification, it should be the same metric value which you can get with `route PRINT -4` command. However, on Windows, higher metric value actually means lower priority, which in this case, a lower metric gateway should be picked instead.

I really enjoy using OpenVPN but I don't have OpenVPN3 development environment so I cannot verify if my thought is correct or not. Please let me know if I was into a wrong way to resolve my issue. Thank you in advance.

**Comment by lstipakov** [comment]
You are definitely right, we should reverse that condition and pick the route entry with the lowest metrics. This will be fixed in the next release.

**Comment by lstipakov** [comment]
@zer0pwned Here is unsigned test build with the fix:

https://staging.openvpn.net/openvpn3/OpenVPN%20Connect%20x64%203.2.2-1579.msi

could you give it a try and see if you could still reproduce the bug?

**Comment by zer0pwned** [comment]
@lstipakov This build works for me! I can use OpenVPN and Zerotier without any issue.
