### ISSUE TITLE
run ovpncli crash.

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#134]
I test ovpncli run well, but some times it will crash.
file: vcpkg\openvpn3\openvpn\tun\win\tunutil.hpp

![image](https://user-images.githubusercontent.com/72748373/101227871-67f4df80-36d4-11eb-929d-f4735470f71c.png)
I can judge the gw variable pointer, What is the reason? Does anyone have an idea?  thanks

**Comment by lstipakov** [comment]
Hi,

This has been fixed recently: https://github.com/OpenVPN/openvpn3/commit/ab90c128916478b8f682e99acddd396e600a59d8
