### ISSUE TITLE
neet root privileges on macos

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#137]
I built openvpn3 with success on macOS, 
But it requires root privileges, for example:
```
sudo ./cli test.ovpn
```
It runs successfully, but using non-administrator rights will fail

```
./cli test.ovpn

```
it failed to run. error log:
```
Tue Jan  5 11:04:56.981 2021 Tue Jan  5 11:04:56.981 2021 TUN Error: utun_error: cannot open available utun device
Tue Jan  5 11:04:56.981 2021 EVENT: TUN_IFACE_CREATE utun_error: cannot open available utun device [FATAL-ERR]
Tue Jan  5 11:04:56.981 2021 EVENT: DISCONNECTED
Tue Jan  5 11:04:56.982 2021 Client exception in transport_recv: tun_exception: not connected
Thread finished
STATS:
  BYTES_IN : 3599
  BYTES_OUT : 2642
  PACKETS_IN : 9
  PACKETS_OUT : 9
  TUN_IFACE_CREATE : 1
```

I want to run cli cmd with non-administrator rights, what should I do. Thank you

**Comment by xiaotudoubaba** [comment]
@ali-reza-zareian ,  thanks,   the post is about windows solution,  
but on masox platform it does not have ovpncliagent.exe .

**Comment by schwabe** [comment]
Yes. The public repository has a no way of running the client without root. There is a 3rd party repository that implemented something with the new mac  VPN API but I can neither remember its name or can had I any look at it and cannot judge its code quality.
