### ISSUE TITLE
Sample usage of the build-linux script under javacli folder?

### ISSUE THREAD

**Issue by woohooyayaya** [OpenVPN/openvpn3#14]
Hi there,
Can you give an example of how to use the build-linux script under the javacli folder?

Thanks a lot.

**Comment by lstipakov** [comment]
Hi,

First, make sure you can build on Linux - follow those steps: https://github.com/OpenVPN/openvpn3/#building-the-openvpn-3-client-on-linux 

Then you need to install swig and gcj:
`$ sudo apt-get install swig gcj-5-jdk`

After that you can execute `build-linux` script. Assuming that you have used same directory structure for Linux build as mentioned in README:
`user@ubuntu:~/ovpn3/core/javacli$ DEP_DIR=/home/user ./build-linux`
