### ISSUE TITLE
how to build macos's ovpnagent.cpp

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#140]
under the ovpn3-core.xcodeproj, I found  the ovpenagent.cpp , but could not found the file,  how to build ovpn3-core project,
![image](https://user-images.githubusercontent.com/72748373/104992171-69e3e980-5a5b-11eb-8bb6-089b4d66d85f.png)

**Comment by dsommers** [comment]
```
$ git ls-files | grep ovpnagent
openvpn/ovpnagent/win/CMakeLists.txt
openvpn/ovpnagent/win/ovpnagent.cpp
```

**Comment by xiaotudoubaba** [comment]
> ```
> $ git ls-files | grep ovpnagent
> openvpn/ovpnagent/win/CMakeLists.txt
> openvpn/ovpnagent/win/ovpnagent.cpp
> ```

thank you ,but this is file support win platform ,  i want to support mac's platform.

**Comment by schwabe** [comment]
The `common` directory in which the sources of the mac agent are located are not open source.
