### ISSUE TITLE
Could not connect vpn after imported profile  |  Error: Open TAP device "" PATH="" FAILED  TUN Error: cannot acquire TAP handle

### ISSUE THREAD

**Issue by gscheartA** [OpenVPN/openvpn3#141]
I have build the openvpn3 code in my PC and debug it in visual studio in the project "ovpncli". I could import the ovpn profile successfully and try to connect vpn. But there is a Error as follow:
Tue Jan 26 18:01:07 2021 TAP ADAPTERS:

Open TAP device "" PATH="" FAILED
Tue Jan 26 18:01:07 2021 TUN Error: cannot acquire TAP handle
Tue Jan 26 18:01:07 2021 EVENT: TUN_IFACE_CREATE cannot acquire TAP handle [FATAL-ERR]
Tue Jan 26 18:01:07 2021 EVENT: DISCONNECTED

Should I do some other steps before debug the source code?

**Comment by dsommers** [comment]
Looks like you try to use `--dev tap` in your configuration, is that right?

OpenVPN 3 does not support TAP devices, only TUN devices (the tap-windows6 driver on Windows supports both TUN and TAP mode, wintun is TUN only).

**Comment by gscheartA** [comment]
@dsommers 
Thank you for your answer. I have checked my profile and the text is "dev tun", loos like not use dev tap. I saw some issues that we should first have tap or wintun driver installed. I have not installed them, I don't know if I should install one of them?

**Comment by gscheartA** [comment]
I have tried installed wintun in my PC and it switched another error. I will submit another issue for current error.
