### ISSUE TITLE
TUN Error: Error registering ring buffers: An attempt was made to perform an initialization operation when initialization has already been completed.

### ISSUE THREAD

**Issue by gscheartA** [OpenVPN/openvpn3#142]
I have installed wintun in my PC and try to test the code from opencli Project. I set a ovpn profile and use "dev tun" in it, together using -w in conmand line. Now the log from the command is as follow:

Successfully flushed the DNS Resolver Cache.
Wed Jan 27 11:27:09 2021 TUN Error: Error registering ring buffers: An attempt was made to perform an initialization operation when initialization has already been completed.
Wed Jan 27 11:27:09 2021 EVENT: TUN_SETUP_FAILED Error registering ring buffers: An attempt was made to perform an initialization operation when initialization has already been completed. [FATAL-ERR]
Wed Jan 27 11:27:09 2021 EVENT: DISCONNECTED
Wed Jan 27 11:27:09 2021 Client exception in transport_recv: tun_exception: not connected
Thread finished
STATS:
  BYTES_IN : 6185
  BYTES_OUT : 2178
  PACKETS_IN : 9
  PACKETS_OUT : 12
  TUN_REGISTER_RINGS_ERROR : 1

Is there any methods to solve this issue? Thank in advance.

**Comment by gscheartA** [comment]
Solved it in my environment. I started the wintun adapter after install, and it cause this error.

**Comment by vishal1kumar** [comment]
Hi gscheart,

I am trying to do the same what you did, running openvpn3 client with wintun driver.
Can you please help me with:
1) How did u install wintun driver on windows?
2) What environment variable did you change to make it work? 

Thanks
Vishal

**Comment by gscheartA** [comment]
Hi @vishal1kumar 
Here are 2 methods for installing wintun driver
1.Directly install it from wintun install package, I think you could get it from their home page
2.Download the wintun driver source code from their git project and build exe, you could call it to install
