### ISSUE TITLE
Option pull-filter is not supported

### ISSUE THREAD

**Issue by stek29** [OpenVPN/openvpn3#144]
I wasn't able to find any references to pull-filter in source code, and it looks like pull-filter is just not implemented in OpenVPN Core

**Comment by dsommers** [comment]
Correct, and @d12fk started looking into this quite recently.

**Comment by gioele** [comment]
It seems that @d12fk has implemented `pull-filter` in commit f6000e1f183f2ba0739eab3f5ec29a94b5863b89.

Is that commit part of a released OpenVPN version?

**Comment by schwabe** [comment]
OpenVPN for Android should also include that version
