### ISSUE TITLE
Make signature inside ExternalPKIBase

### ISSUE THREAD

**Issue by aevtyushin** [OpenVPN/openvpn3#155]
Hi,

I have a question regarding the ExternalPKIBase class:

![image](https://user-images.githubusercontent.com/35372328/114187755-04641280-9951-11eb-9621-ebabaf10dca0.png)

Is there an example of code in **C**, **C++**, **Objective-C** or **Swift** that would allow to understand how to properly sign a message?
 
All my attempts to generate a signature myself ended in error.
In the logs on the server, I see the following:

> Fri Apr 9 15:51:42 2021 us = 76461 185.6.245.142:65456 OpenSSL: error: 0407006A: rsa routines: RSA_padding_check_PKCS1_type_1: block type is not 01
> Fri Apr 9 15:51:42 2021 us = 76485 185.6.245.142:65456 OpenSSL: error: 04067072: rsa routines: RSA_EAY_PUBLIC_DECRYPT: padding check failed
> Fri Apr 9 15:51:42 2021 us = 76501 185.6.245.142:65456 OpenSSL: error: 1408807B: SSL routines: ssl3_get_cert_verify: bad signature
> Fri Apr 9 15:51:42 2021 us = 76516 185.6.245.142:65456 OpenSSL: error: 140940E5: SSL routines: ssl3_read_bytes: ssl handshake failure

If I pass the private key and certificate ("key", "cert") to **config.contentList**, as a string, then everything works.

Here's an example of my method for signing:

`+ (NSString*)signString:(NSString*)string
         withPrivateKey:(NSString*)privateKey
                  error:(NSError**)error {
 
    int retEr;
    char* text = (char*) [string UTF8String];
    unsigned char *data;
    unsigned int dataLen;
    
    // converting nsstring base64 private key to openssl RSA key
    
    BIO *mem = NULL;
    RSA *rsa_private = NULL;
    char *private_key = (char*)[privateKey UTF8String];
    
    mem = BIO_new_mem_buf(private_key, strlen(private_key));
    if (mem == NULL)
    {
        char buffer[120];
        ERR_error_string(ERR_get_error(), buffer);
        fprintf(stderr, "OpenSSL error: %s", buffer);
        return @"";
    }
    
    rsa_private = PEM_read_bio_RSAPrivateKey(mem, NULL, NULL, NULL);
    BIO_free (mem);
    if (rsa_private == NULL)
    {
        char buffer[120];
        ERR_error_string(ERR_get_error(), buffer);
        fprintf(stderr, "OpenSSL error: %s", buffer);
        return @"";
    }
    // end of convertion
    
    data = (unsigned char *) text;
    dataLen = strlen(text);
    
    // creating signature
        
    // sha256
    unsigned char hash[SHA256_DIGEST_LENGTH];
    unsigned char sign[256];
    unsigned int signLen;
    SHA256(data, dataLen, hash);
    //  signing
    retEr = RSA_sign(NID_sha256, hash, SHA256_DIGEST_LENGTH, sign, &signLen, rsa_private);
    
     printf("RSA_sign: %s\n", (retEr == 1) ? "RSA_sign success" : "RSA_sign error");
    
    //  convert unsigned char -> std:string
    std::stringstream buffer;
    for (int i = 0; i < 128; i++)
    {
        buffer << std::hex << std::setfill('0');
        buffer << std::setw(2)  << static_cast<unsigned>(sign[i]);
    }
    std::string signature = buffer.str();
    
    NSData *signatureData = [NSData dataWithBytes:signature.data() length:signature.length()];
    NSString *signatureBase64 = [signatureData base64EncodedStringWithOptions:0];
        
    RSA_free(rsa_private);
    
    return signatureBase64;
    
}
`
My config file looks like this
```
remote example.com
client
dev tun
tls-client
remote-cert-tls server
proto tcp-client
route-method exe
route-delay 2
resolv-retry infinite
nobind
persist-key
persist-tun
auth-user-pass
auth-nocache
reneg-sec 0
verb 3
cipher AES-256-CBC
explicit-exit-notify 1
<ca>
-----BEGIN CERTIFICATE-----
MIIDJDCCAgygAw....==
-----END CERTIFICATE-----
</ca>
route-nopull
route-metric 50
route-nopull 1
```

**Comment by schwabe** [comment]
I can offer Java:

https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/ui/java/de/blinkt/openvpn/core/OpenVPNThreadv3.java#L229

https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/main/java/de/blinkt/openvpn/VpnProfile.java#L1164

You are doing completely wrong signatures compared to what the crypto library expects.

https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/main/cpp/jbcrypto/jbcrypto.cpp

Here is hacky code around a bug in jellybean that uses RSA_private_encrypt

The openvpn documentation should also be helpful. The data that openvpn2 expects is the same: https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt#L940

**Comment by aevtyushin** [comment]
Thanks,

Does the result of executing function  
`mVp.getSignedData(mService, signreq.getData(), true)`

equivalent to command?
`openssl rsautl -sign -pkcs -inkey key.key -in sign.txt -out sign.rsa.txt`

**Comment by aevtyushin** [comment]
> I can offer Java:
> 
> https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/ui/java/de/blinkt/openvpn/core/OpenVPNThreadv3.java#L229
> 
> https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/main/java/de/blinkt/openvpn/VpnProfile.java#L1164
> 
> https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/main/java/de/blinkt/openvpn/VpnProfile.java#L1195
> 
> You are doing completely wrong signatures compared to what the crypto library expects.
> 
> Here is hacky code around a bug in jellybean that uses RSA_private_encrypt:
> https://github.com/schwabe/ics-openvpn/blob/5387d827f16b0fb9cfa7cbda1f4d6d245eff3382/main/src/main/cpp/jbcrypto/jbcrypto.cpp
> 
> The openvpn documentation should also be helpful. The data that openvpn2 expects is the same: https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt#L940
> 
> Hope that helps

Thanks,

Does the result of executing function  
`mVp.getSignedData(mService, signreq.getData(), true)`

equivalent to command?
`openssl rsautl -sign -pkcs -inkey key.key -in sign.txt -out sign.rsa.txt`

**Comment by schwabe** [comment]
No. It is not. The signature that the rsautil does is different.
