### ISSUE TITLE
On Windows, jsoncpp is missing

### ISSUE THREAD

**Issue by datajango** [OpenVPN/openvpn3#157]
change README.rst
line 206 from     > vcpkg install openssl-windows:x64-windows asio:x64-windows tap-windows6:x64-windows lz4:x64-windows gtest:x64-windows
to 
vcpkg install openssl-windows:x64-windows asio:x64-windows tap-windows6:x64-windows lz4:x64-windows gtest:x64-windows jsoncpp:x64-windows

**Comment by lstipakov** [comment]
Hi, thanks for the report. We've switched to vcpkg manifest mode for managing dependencies. Problem should be now fixed.
