### ISSUE TITLE
WRAP errors

### ISSUE THREAD

**Issue by dictory99** [OpenVPN/openvpn3#159]
Hi guys!
Can you help me please. I'm trying to build linux library, but always have the same error.
I used insructions from main page. Ubuntu 20.04 VirtualBox (clean, updated ).

`root@riddick-VirtualBox:~/O3/core/javacli# ./build-linux
SWIG
JAVA
CORE
WRAP
In file included from /root/O3/core/openvpn/addr/ipv4.hpp:39,
                 from /root/O3/core/openvpn/addr/ip.hpp:34,
                 from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/iperr.hpp:65:17: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
   65 |           const openvpn_io::error_code& ec)
      |                 ^~~~~~~~~~
      |                 openvpn
/root/O3/core/openvpn/addr/iperr.hpp:65:39: error: expected unqualified-id before ‘&’ token
   65 |           const openvpn_io::error_code& ec)
      |                                       ^
/root/O3/core/openvpn/addr/iperr.hpp:65:39: error: expected ‘)’ before ‘&’ token
   65 |           const openvpn_io::error_code& ec)
      |                                       ^
      |                                       )
/root/O3/core/openvpn/addr/iperr.hpp:62:38: note: to match this ‘(’
   62 |       inline std::string format_error(const std::string& ipstr,
      |                                      ^
/root/O3/core/openvpn/addr/iperr.hpp:65:41: error: expected initializer before ‘ec’
   65 |           const openvpn_io::error_code& ec)
      |                                         ^~
In file included from /root/O3/core/openvpn/addr/ip.hpp:34,
                 from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/ipv4.hpp:289:35: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  289 |       static Addr from_asio(const openvpn_io::ip::address_v4& asio_addr)
      |                                   ^~~~~~~~~~
      |                                   openvpn
/root/O3/core/openvpn/addr/ipv4.hpp:289:49: error: expected unqualified-id before ‘::’ token
  289 |       static Addr from_asio(const openvpn_io::ip::address_v4& asio_addr)
      |                                                 ^~
/root/O3/core/openvpn/addr/ipv4.hpp:289:49: error: expected ‘)’ before ‘::’ token
  289 |       static Addr from_asio(const openvpn_io::ip::address_v4& asio_addr)
      |                            ~                    ^~
      |                                                 )
/root/O3/core/openvpn/addr/ipv4.hpp:289:47: error: expected ‘;’ at end of member declaration
  289 |       static Addr from_asio(const openvpn_io::ip::address_v4& asio_addr)
      |                                               ^~
      |                                                 ;
/root/O3/core/openvpn/addr/ipv4.hpp:289:51: error: ‘address_v4’ in namespace ‘::’ does not name a type
  289 |       static Addr from_asio(const openvpn_io::ip::address_v4& asio_addr)
      |                                                   ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv4.hpp:296:7: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  296 |       openvpn_io::ip::address_v4 to_asio() const
      |       ^~~~~~~~~~
      |       openvpn
/root/O3/core/openvpn/addr/ipv4.hpp: In static member function ‘static openvpn::IPv4::Addr openvpn::IPv4::Addr::from_string(const string&, const TITLE&)’:
/root/O3/core/openvpn/addr/ipv4.hpp:212:2: error: ‘openvpn_io’ has not been declared
  212 |  openvpn_io::error_code ec;
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv4.hpp:213:2: error: ‘openvpn_io’ has not been declared
  213 |  openvpn_io::ip::address_v4 a = openvpn_io::ip::make_address_v4(ipstr, ec);
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv4.hpp:214:6: error: ‘ec’ was not declared in this scope
  214 |  if (ec)
      |      ^~
/root/O3/core/openvpn/addr/ipv4.hpp:216:19: error: ‘a’ was not declared in this scope
  216 |  return from_asio(a);
      |                   ^
/root/O3/core/openvpn/addr/ipv4.hpp: In member function ‘std::string openvpn::IPv4::Addr::to_string() const’:
/root/O3/core/openvpn/addr/ipv4.hpp:226:8: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  226 |  const openvpn_io::ip::address_v4 a = to_asio();
      |        ^~~~~~~~~~
      |        openvpn
/root/O3/core/openvpn/addr/ipv4.hpp:227:20: error: ‘a’ was not declared in this scope
  227 |  std::string ret = a.to_string();
      |                    ^
In file included from /root/O3/core/openvpn/addr/ip.hpp:35,
                 from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/ipv6.hpp: At global scope:
/root/O3/core/openvpn/addr/ipv6.hpp:236:35: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  236 |       static Addr from_asio(const openvpn_io::ip::address_v6& asio_addr)
      |                                   ^~~~~~~~~~
      |                                   openvpn
/root/O3/core/openvpn/addr/ipv6.hpp:236:49: error: expected unqualified-id before ‘::’ token
  236 |       static Addr from_asio(const openvpn_io::ip::address_v6& asio_addr)
      |                                                 ^~
/root/O3/core/openvpn/addr/ipv6.hpp:236:49: error: expected ‘)’ before ‘::’ token
  236 |       static Addr from_asio(const openvpn_io::ip::address_v6& asio_addr)
      |                            ~                    ^~
      |                                                 )
/root/O3/core/openvpn/addr/ipv6.hpp:236:47: error: expected ‘;’ at end of member declaration
  236 |       static Addr from_asio(const openvpn_io::ip::address_v6& asio_addr)
      |                                               ^~
      |                                                 ;
/root/O3/core/openvpn/addr/ipv6.hpp:236:51: error: ‘address_v6’ in namespace ‘::’ does not name a type
  236 |       static Addr from_asio(const openvpn_io::ip::address_v6& asio_addr)
      |                                                   ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv6.hpp:279:7: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  279 |       openvpn_io::ip::address_v6 to_asio() const
      |       ^~~~~~~~~~
      |       openvpn
/root/O3/core/openvpn/addr/ipv6.hpp:698:2: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  698 |  openvpn_io::ip::address_v6::bytes_type asio_bytes;
      |  ^~~~~~~~~~
      |  openvpn
/root/O3/core/openvpn/addr/ipv6.hpp: In static member function ‘static openvpn::IPv6::Addr openvpn::IPv6::Addr::from_string(const string&, const TITLE&)’:
/root/O3/core/openvpn/addr/ipv6.hpp:106:2: error: ‘openvpn_io’ has not been declared
  106 |  openvpn_io::error_code ec;
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv6.hpp:107:2: error: ‘openvpn_io’ has not been declared
  107 |  openvpn_io::ip::address_v6 a = openvpn_io::ip::make_address_v6(ipstr, ec);
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ipv6.hpp:108:6: error: ‘ec’ was not declared in this scope
  108 |  if (ec)
      |      ^~
/root/O3/core/openvpn/addr/ipv6.hpp:110:19: error: ‘a’ was not declared in this scope
  110 |  return from_asio(a);
      |                   ^
/root/O3/core/openvpn/addr/ipv6.hpp: In member function ‘std::string openvpn::IPv6::Addr::to_string() const’:
/root/O3/core/openvpn/addr/ipv6.hpp:120:8: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  120 |  const openvpn_io::ip::address_v6 a = to_asio();
      |        ^~~~~~~~~~
      |        openvpn
/root/O3/core/openvpn/addr/ipv6.hpp:121:20: error: ‘a’ was not declared in this scope
  121 |  std::string ret = a.to_string();
      |                    ^
In file included from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/ip.hpp: At global scope:
/root/O3/core/openvpn/addr/ip.hpp:469:35: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  469 |       static Addr from_asio(const openvpn_io::ip::address& addr)
      |                                   ^~~~~~~~~~
      |                                   openvpn
/root/O3/core/openvpn/addr/ip.hpp:469:49: error: expected unqualified-id before ‘::’ token
  469 |       static Addr from_asio(const openvpn_io::ip::address& addr)
      |                                                 ^~
/root/O3/core/openvpn/addr/ip.hpp:469:49: error: expected ‘)’ before ‘::’ token
  469 |       static Addr from_asio(const openvpn_io::ip::address& addr)
      |                            ~                    ^~
      |                                                 )
/root/O3/core/openvpn/addr/ip.hpp:469:47: error: expected ‘;’ at end of member declaration
  469 |       static Addr from_asio(const openvpn_io::ip::address& addr)
      |                                               ^~
      |                                                 ;
/root/O3/core/openvpn/addr/ip.hpp:469:51: error: ‘address’ in namespace ‘::’ does not name a type
  469 |       static Addr from_asio(const openvpn_io::ip::address& addr)
      |                                                   ^~~~~~~
/root/O3/core/openvpn/addr/ip.hpp:489:7: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  489 |       openvpn_io::ip::address to_asio() const
      |       ^~~~~~~~~~
      |       openvpn
In file included from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/ip.hpp: In static member function ‘static openvpn::IP::Addr openvpn::IP::Addr::from_string(const string&, const TITLE&, openvpn::IP::Addr::Version)’:
/root/O3/core/openvpn/addr/ip.hpp:110:2: error: ‘openvpn_io’ has not been declared
  110 |  openvpn_io::error_code ec;
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ip.hpp:111:2: error: ‘openvpn_io’ has not been declared
  111 |  openvpn_io::ip::address a = openvpn_io::ip::make_address(ipstr, ec);
      |  ^~~~~~~~~~
/root/O3/core/openvpn/addr/ip.hpp:112:6: error: ‘ec’ was not declared in this scope
  112 |  if (ec)
      |      ^~
/root/O3/core/openvpn/addr/ip.hpp:114:29: error: ‘a’ was not declared in this scope
  114 |  const Addr ret = from_asio(a);
      |                             ^
In file included from /root/O3/core/openvpn/tun/builder/base.hpp:31,
                 from /root/O3/core/client/ovpncli.hpp:31,
                 from ovpncli_wrap.cxx:764:
/root/O3/core/openvpn/addr/ip.hpp: In static member function ‘static bool openvpn::IP::Addr::is_valid(const string&)’:
/root/O3/core/openvpn/addr/ip.hpp:173:4: error: ‘openvpn_io’ has not been declared
  173 |    openvpn_io::error_code ec;
      |    ^~~~~~~~~~
/root/O3/core/openvpn/addr/ip.hpp:174:4: error: ‘openvpn_io’ has not been declared
  174 |    openvpn_io::ip::make_address(ipstr, ec);
      |    ^~~~~~~~~~
/root/O3/core/openvpn/addr/ip.hpp:174:40: error: ‘ec’ was not declared in this scope
  174 |    openvpn_io::ip::make_address(ipstr, ec);
      |                                        ^~
/root/O3/core/openvpn/addr/ip.hpp: In member function ‘std::string openvpn::IP::Addr::to_string() const’:
/root/O3/core/openvpn/addr/ip.hpp:430:12: error: ‘openvpn_io’ does not name a type; did you mean ‘openvpn’?
  430 |      const openvpn_io::ip::address a = to_asio();
      |            ^~~~~~~~~~
      |            openvpn
/root/O3/core/openvpn/addr/ip.hpp:431:24: error: ‘a’ was not declared in this scope
  431 |      std::string ret = a.to_string();
`

Thanks!

**Comment by dsommers** [comment]
Please, when providing log data or console outputs .... at least make sure it is readable.  I'm closing this and it can be reopened once we have something which is readable.
