### ISSUE TITLE
last release build could not build on windows x64

### ISSUE THREAD

**Issue by gscheartA** [OpenVPN/openvpn3#161]
![image](https://user-images.githubusercontent.com/74002809/120574359-c1568500-c451-11eb-976f-9029bcb65078.png)

Here is the error code:
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory	ovpncliagent	E:\openvpn3-build\openvpn3\openvpn\common\peercred.hpp	25	

Could you please kindly help about it? Thank you.

**Comment by lstipakov** [comment]
Hi,

Looks like you are using ASIO 1.18, which added support of UNIX domain sockets to Windows (https://github.com/chriskohlhoff/asio/commit/34c39d923d125010f1d5b1a32a4e0fe1ddb9ebec) and our codebase is not yet ready for that.

Please note that the recommended way of handling dependencies is to use vcpkg. We have our own ASIO port based on 1.14, which which doesn't have this issue. 

We'll upgrade dependencies and support for ASIO 1.18.

**Comment by lstipakov** [comment]
This should be now fixed.
