### ISSUE TITLE
Could openvpn3 code be extended to desktop?

### ISSUE THREAD

**Issue by lucaszanella** [OpenVPN/openvpn3#162]
I'm integrating this code into my app. For desktop, however, it won't compile because of lzo and lz4. The failure is because it expects `ANDROID_ABI` to be set.

Would a PR making it buildable in desktop be welcome?

**Comment by schwabe** [comment]
The code is already used in non Android programs. And grepping through the code for ANDROID_ABI gives me also zero hits.

Note that you include this code in your app that your app will become subject to the AGPL3.

**Comment by lucaszanella** [comment]
wtf I meant to comment on https://github.com/ProtonVPN/android-app/ sorry

**Comment by lucaszanella** [comment]
@schwabe by the way, I went to https://github.com/ProtonVPN/android-app/ for android because when I tried to compile this repo to android I got problems with lzo and lz4 missing. For desktop they are available because ubuntu has the -dev versions for these libs, but what about compiling for android on x64 ubuntu? For the proton vpn app these are compiled together with the openvpn3 lib

**Comment by schwabe** [comment]
I have no idea about the proton app but usually on android the project has to include/compile them as well, my Android app does it as well.
