### ISSUE TITLE
allow-pull-fqdn params parse error.

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#163]
hi I use allow-pull-fqdn , and route ip138.com 255.255.255.255 vpn_gateway,
the error log:
Thu Jul  8 10:34:42.333 2021 exception parsing IPv4 route: [route] [ip138.com] [255.255.255.255] [vpn_gateway] : addr_pair_mask_parse_error: AddrMaskPair parse error 'route': ip138.com/255.255.255.255 : ip_exception: error parsing route IP address 'ip138.com' : Invalid argument

here is my ovpn config:
```
 client
 dev tun
 proto tcp
 remote 219.135.99.136 1194
 resolv-retry infinite
 remote-cert-tls server
 nobind
 persist-key
 persist-tun
 #ca ca.crt
 #cert devchenqian3.crt
 #key devchenqian3.key
 #tls-auth ta.key 1
 comp-lzo
 verb 3

 resolv-retry infinite
## ------------------------
 allow-pull-fqdn
 route ip138.com 255.255.255.255 vpn_gateway
## ------------------------
 nobind
 persist-key
 persist-tun
<ca>
...
</ca>
```

error log:
---

Thu Jul  8 10:34:42.281 2021 SSL Handshake: TLSv1.2/TLS-DHE-RSA-WITH-AES-256-GCM-SHA384
Thu Jul  8 10:34:42.281 2021 Session is ACTIVE
Thu Jul  8 10:34:42.281 2021 EVENT: GET_CONFIG
Thu Jul  8 10:34:42.281 2021 Sending PUSH_REQUEST to server...
Thu Jul  8 10:34:42.333 2021 OPTIONS:
0 [route] [ip138.com] [255.255.255.255] [vpn_gateway]
1 [redirect-gateway] [def1] [bypass-dhcp]
2 [dhcp-option] [DNS] [123.1.1.2]
3 [route] [10.8.0.1]
4 [topology] [net30]
5 [ping] [10]
6 [ping-restart] [120]
7 [route] [10.203.18.0] [255.255.255.0] [net_gateway]
8 [route] [122.225.83.0] [255.255.255.0] [net_gateway]
9 [route] [10.103.2.0] [255.255.255.0] [net_gateway]
10 [route] [10.102.100.0] [255.255.255.0] [net_gateway]
11 [route] [10.0.0.0] [255.0.0.0] [net_gateway]
12 [route] [20.197.80.0] [255.255.255.0] [net_gateway]
13 [dhcp-option] [DNS] [10.103.2.13]
14 [ifconfig] [10.8.0.186] [10.8.0.185]

Thu Jul  8 10:34:42.333 2021 PROTOCOL OPTIONS:
  cipher: BF-CBC
  digest: SHA1
  key-derivation: OpenVPN PRF
  compress: LZO_STUB
  peer ID: -1
  control channel: tls-auth enabled
Thu Jul  8 10:34:42.333 2021 TunPersist: short-term connection scope
Thu Jul  8 10:34:42.333 2021 TunPersist: new tun context
Thu Jul  8 10:34:42.333 2021 EVENT: ASSIGN_IP
**Thu Jul  8 10:34:42.333 2021 exception parsing IPv4 route: [route] [ip138.com] [255.255.255.255] [vpn_gateway] : addr_pair_mask_parse_error: AddrMaskPair parse error 'route': ip138.com/255.255.255.255 : ip_exception: error parsing route IP address 'ip138.com' : Invalid argument**
Thu Jul  8 10:34:42.333 2021 CAPTURED OPTIONS:

**Comment by schwabe** [comment]
The option allow-pull-fqdn is not support in OpenVPN3

**Comment by xiaotudoubaba** [comment]
ok. thanks.

**Comment by kaspergrubbe** [comment]
@schwabe Are there any plans on supporting it? It is a really handy feature to have since some of our services changes IP quite often.

Someone proposed a script like this as a hack:

```
#!/bin/bash
cp ~/secrets/billetto.ovpn /tmp/billetto.ovpn     
       
for ip in `dig a +short billetto.dk`; do
  echo "route $ip" >> /tmp/billetto.ovpn
done   

sudo openvpn /tmp/billetto.ovpn
```

Having the `allow-pull-fqdn` helps us simplify our setup.

**Comment by schwabe** [comment]
No, see also #195
