### ISSUE TITLE
Update broke client on Linux

### ISSUE THREAD

**Issue by jyscao** [OpenVPN/openvpn3#164]
I'm on Ubuntu 20.04, and upgraded to `14~beta+focal` recently, which broke my VPN connectivity. Downgrading to `13~beta-1+focal` resolved the issue. Here's a [Server Fault question](https://serverfault.com/questions/1069414/openvpn-client-session-start-error-failed-to-start-new-session-failed) I created in regards to this.

I'm good for day-to-day usage again on my end, just wanted to let you guys know.

**Comment by zarraozaga** [comment]
Hi @jyscao I am also facing this issue. Did you get this error? 

`session-start: ** ERROR ** Failed to start new session: Failed calling D-Bus method Connect: Timeout was reached`

**Comment by jyscao** [comment]
I worked around it by downgrading the package version.

**Comment by zarraozaga** [comment]
Can let me know how to downgrade the package version? I installed openvpn3 client using this website. https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

Not sure how to downgrade or select specific version

**Comment by zarraozaga** [comment]
okay i found it, for those viewing this thread. 

`sudo apt install openvpn3=13~beta-1+focal`

**Comment by dsommers** [comment]
Closing this, as this issue is already tracked in the proper project; openvpn3-linux under [issue 55](https://github.com/OpenVPN/openvpn3-linux/issues/55)
