### ISSUE TITLE
[linux] build fails with gtest v1.10.0

### ISSUE THREAD

**Issue by Horki** [OpenVPN/openvpn3#165]
On linux `5.12.15-arch1-1`, openvpn3 fails to build due to gtest `v1.10.0` related errors, fix was made when update to `v1.11.0`

```
horky@horkyhost ~/O3/core/build (git)-[master] % cmake --build .

[  4%] Building CXX object test/unittests/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from $USER/O3/core/build/test/unittests/googletest-src/googletest/src/gtest-all.cc:42:
$USER/O3/core/build/test/unittests/googletest-src/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
$USER/O3/core/build/test/unittests/googletest-src/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
$USER/O3/core/build/test/unittests/googletest-src/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
$USER/O3/core/build/test/unittests/googletest-src/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
 1299 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [test/unittests/googletest-build/googletest/CMakeFiles/gtest.dir/build.make:76: test/unittests/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:292: test/unittests/googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by dsommers** [comment]
This should be resolved, as the gtest suite has been updated a while back.

**Comment by Horki** [comment]
Thanks for post-poned reply 🙄

**Comment by dsommers** [comment]
Sorry for letting it linger so long. But as stated in [CONTRIBUTING.rst](https://github.com/OpenVPN/openvpn3/blob/master/CONTRIBUTING.rst#contributing-to-openvpn-3):

> Patches can be sent as GitHub pull requests for initial reviews and discussion. Final patches from the community which modifies code must be sent to the [openvpn-devel@lists.sourceforge.net](mailto:openvpn-devel@lists.sourceforge.net) mailing list before being accepted.

We do not focus that much on the GH pull-reqs, as we want community contributions to be preserved on public mailing lists; which are widely distributed.  GH pull-reqs are mainly used for discussions and initial review.

**Comment by Horki** [comment]
For non-discussion and non-initial review?

**Comment by dsommers** [comment]
Normally, yes.  I see there was no response to the pull-req in this case, which is very unfortunate. In addition it got fixed after your pull-request on when our own (and at that time new) employees hit a related issue, which went through internal review before merge.

But generally speaking, just sending a pull-request isn't a guarantee we will catch it in a timely manner.  It is highly recommended to initiate discussions on the mailing list (which can be made clearer in the CONTRIBUTING.rst doc), where far more developers pay attention and follow up.
