### ISSUE TITLE
Shared library libprotobuf not available with old refferral

### ISSUE THREAD

**Issue by emollusion** [OpenVPN/openvpn3#167]
Hi!

I believe the error occured after a kernel upgrade.
It seems like openvpn3 is looking for specific version of files in the shared library of libprotobuf.
Specifically looking for
/usr/lib/libprotobuf.so.27

Error I received was:
```
net.openvpn.v3.sessions[7348]: /usr/libexec/openvpn3-linux/openvpn3-service-sessionmgr: error while loading shared libraries:  error while loading shared libraries: libprotobuf.so.27: cannot open shared object file: No such file or directory
dbus-daemon[481]: [system] Activated service 'net.openvpn.v3.sessions' failed: Launch helper exited with unknown return code 127
```
After the upgrade, the available version of libprotobuf is 28, which is reffered to by a relative links:
```
/usr/lib/libprotobuf.so -> libprotobuf.so.28.0.3
/usr/lib/libprotobuf.so.28 -> libprotobuf.so.28.0.3
```
I believe that openvpn3 should be looking for /usr/lib/libprotobuf.so instead of the specific version /usr/lib/libprotobuf.so.27
I solved my problem by pointing a new relative link:
```
/usr/lib/libprotobuf.so.27 -> libprotobuf.so
```
So this wont happen again if the kernels are upgraded before openvpn3 is.

(not often I report things, So I hope this is the right place for this issue, otherwise please refer me to the correct place)
Thank you!

**Comment by schwabe** [comment]
What operating system is this on? Also normally a change in the number at the end of a library means a ABI change. While the change might be small enough here that you are lucky that it still works, in general that this is not true. So linking against the `ibprotobuf.so.27` instead `ibprotobuf.so` is from what  I understand correct.

**Comment by emollusion** [comment]
I am running Manjaro.

So I suppose this is not a problem by design, but an update needed to comply with libprotobuf.so.28 ?

Yeah, might very well have been updates along side the kernel :)

**Comment by schwabe** [comment]
well basically openvpn3-linux needs to be recompiled. Did you compiled openvpn3-linux from sources?

**Comment by emollusion** [comment]
No, I have not compiled openvpn3.

**Comment by schwabe** [comment]
We don't distribute openvpn3-linux ourselves for Manjaro. It shoulds however packaged openvpn3-linux for your operating system is to blame for this. Google says Manjaro is based on arch and on the [arch package page](https://aur.archlinux.org/packages/openvpn3/) there is even a comment pointing out that this dependency is missing.

**Comment by emollusion** [comment]
Ah, ok, so this was maybe not the correct place to point out this "error".
Thank you for your time and answer!
