### ISSUE TITLE
How to get wintun driver for ovpncli client

### ISSUE THREAD

**Issue by vishal1kumar** [OpenVPN/openvpn3#168]
Many have asked similar questions earlier, sorry if this has been clarified/answered already. 
**I need an independent method to get wintun driver for the ovpncli client on windows 10 test machine.** 

Other methods which I saw people using, to 1st install 'Windows 64-bit MSI installer' which installs 'openvpn-gui' along with wintun network driver. But I dont want to install another openvpn-gui client to just get the wintun driver.

From 'https://www.wintun.net/' they provide the platform dependent 'wintun.dll' and header file, but it is not clear how we need to integrate this with ovpncli project. 

I also tried to build wintun on my own using VS2019 and WDK1903 but it is giving me below error:
`Error	C1083	Cannot open include file: 'wintun-inf.h': No such file or directory`
`Error	C4013	'ExAllocatePoolZero' undefined; assuming extern returning int`

Can someone please help me with steps with which I can independently install wintun driver, like we have for the tap driver available at: 'https://build.openvpn.net/downloads/releases/'.

TIA.

**Comment by lstipakov** [comment]
Hi,

Please be aware that drivers distribution (tap-windows6, wintun, ovpn-dco) is outside of scope of openvpn3 project, which is, first of all, a library.

Both openvpn2 and openvpn3 support wintun 0.8. More recent versions have changed distribution model and introduced middleware API which is not supported by openvpn, although openvpn still can talk to wintun via DeviceIOControl calls.

I am not aware of openvpn3-based clients with wintun support. If you want to try ovpncli with wintun, the easiest way indeed would be to install openvpn-gui (which installs wintun driver) or download https://www.wintun.net/builds/wintun-amd64-0.8.1.msm and extract/install wintun driver manually.

**Comment by vishal1kumar** [comment]
Thanks for your response Stipakov. ovpncli is working fine with wintun (installed using openvpn-gui). It is working like a charm.
I also tried to measure the performance difference between Tap and Tun driver, which I didnt find any. Possibly in stress testing we may see significant performance improvement with wintun driver.

If someone can help me in rectifying below error while compiling Wintun code. I will also try to find the discussion forum for wintun to post this question:
```
Error C1083 Cannot open include file: 'wintun-inf.h': No such file or directory
Error C4013 'ExAllocatePoolZero' undefined; assuming extern returning int
```

I will close this bug as this is not relevent for openvpn as Stipakov has mentioned
