### ISSUE TITLE
Building for iOS

### ISSUE THREAD

**Issue by j-cimb-barker** [OpenVPN/openvpn3#17]
I've seen evidence that people have got this to work on iOS. How are they building it...? I can build and run cli on my Mac just fine. However I have hit a wall trying to build the library for iOS.

Can anyone share how they did this...?

Many thanks, Joel

**Comment by dsommers** [comment]
Closing as not an issue.  This is not a support forum.

This openvpn3 git repository contains the OpenVPN 3 Core library.  This means that it is just a library which can be used when implementing an OpenVPN 3 based client.  This is not a fully fledged end-user ready client with an interface.  The test/ovpncli/cli client is just a test client.
