### ISSUE TITLE
How to build for Android?

### ISSUE THREAD

**Issue by pokamest** [OpenVPN/openvpn3#171]
Are there some manuals how to build openvpn for Android?
I tried to run javacli/build-android  script but getting error
```
~/O3/core/javacli$ ./build-android
./build-android: line 12: vars/android-sdk-path: No such file or directory
```

**Comment by schwabe** [comment]
You can check out schwabe/ics-openvpn

**Comment by schwabe** [comment]
Closing due to no further response from submitter and giving a solution

**Comment by scruel** [comment]
Same issue here...
