### ISSUE TITLE
Windows Server 2019 OpenVPNConnect.exe --disconnect-shortcut=XXXXXX NotWork

### ISSUE THREAD

**Issue by lucaswhob** [OpenVPN/openvpn3#172]
Hello
I Run This Command with cmd is ok 
OpenVPNConnect.exe --disconnect-shortcut=1628621371733
and disconnect Work fine
but when run this same command from C# Not Work 
I Wrote C# Console Application Run Ok in windows 7 but on windows Server 2019 Not Work

**Comment by ordex** [comment]
Hello,
This issue tracker is for the OpenVPN3 library only. OpenVPN Connect is a software developed by OpenVPN Inc.
For support with OpenVPN Connect, please open a ticket on https://openvpn.net/support

Regards,
