### ISSUE TITLE
Status bar icon on Mac on Apple Silicon always dark

### ISSUE THREAD

**Issue by blayson** [OpenVPN/openvpn3#174]
On macOS Big Sur running on the m1 icon in the status bar is always dark (gray). In the themes settings section, there is a default and dark option which leads to the same icon appearance.
![image](https://user-images.githubusercontent.com/17512747/134335525-bb8c4a9d-7d31-4e33-9f86-193bb8398f96.png)
![image](https://user-images.githubusercontent.com/17512747/134335790-556d389b-d148-45dc-9752-c67ef994502e.png)

**Comment by schwabe** [comment]
This is about the openvpn3 library and not a specific client. I will however forward that to the OpenVPN connect team. In future please use support@openvpn.net for questions regarding OpenVPN Connect.
