### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by ziedrv** [OpenVPN/openvpn3#183]
Hello Guys,
I think there is a bug with OpenVPN Connect (iOS, Linux and Windows)
I am setting up a multi-factor authentication with Azure AD. it works perfectly with OpenVPN-gui but only in Windows.
When I tried OpenVPN Connect in Mac OS or Linux even Windows, I got a weird behavior:

**1. Asking to authenticate twice:**
When I authenticate the first time with an Azure AD account, it asks to login with a device code. When I did that it shows the Multi-factor authentication again with a different code and then at the second retry the client will connect.

![100230](https://user-images.githubusercontent.com/24189414/144231830-f1cbc232-b340-4f5e-bd34-76faf0e03adb.PNG)

**2. OpenVPN Connect required a response:**
Actually the authentication doesn't need a code or something to enter after getting a valid token from [_microsoft.com/devicelogin_]
But OpenVPN Connect client required enter something (even 123)
This behavior doesn't exist in OpenVPN-gui

![100231](https://user-images.githubusercontent.com/24189414/144231856-3ce772ae-eeb3-4c20-a89c-499314a99732.PNG)

**Comment by ej-navarro** [comment]
Hi @ziedrv , please open a ticket directly with OpenVPN Support Center **[HERE](https://support.openvpn.com/hc/en-us)**. and provide all necessary information (i.e. client and server logs, server configuration etc...). Will be monitoring your ticket and provide response as soon as we have it on our support queue. Thank you!
