### ISSUE TITLE
Socks proxy support is currently not supported

### ISSUE THREAD

**Issue by pokamest** [OpenVPN/openvpn3#188]
According [this](https://openvpn.net/vpn-server-resources/faq-regarding-openvpn-connect-ios/)
> socks-proxy — Socks proxy support is currently not supported

Any plans to support socks proxy for iOS?

**Comment by dsommers** [comment]
There are very few requests for Socks Proxy support, that is not something we will put much efforts into unless there comes patches from the community we can review and merge from patches to the devel mailing list.  See our [development model document](https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation#Developmentprocesses) for more details..
