### ISSUE TITLE
addr_pair_mask_parse_error

### ISSUE THREAD

**Issue by oawang** [OpenVPN/openvpn3#189]
exception parsing IPv4 route: [route] [mysql.rds.aliyuncs.com] [255.255.255.255] [vpn_gateway]  : addr_pair_mask_parse_error: AddrMaskPair parse error 'route': mysql.rds.aliyuncs.com/255.255.255.255 : ip_exception: error parsing route IP address 'mysql.rds.aliyuncs.com' : An invalid argument was supplied.

**Comment by oawang** [comment]
allow-pull-fqdn

push "route mysql.rds.aliyuncs.com 255.255.0.0"

**Comment by oawang** [comment]
vpn client:
windows openvpn3

**Comment by schwabe** [comment]
duplicate of #163

**Comment by oawang** [comment]
Without this configuration, same error reported

**Comment by oawang** [comment]
allow-pull-fqdn
Without this configuration, same error reported

**Comment by schwabe** [comment]
domain names in route statements are not supported in openvpn3 and will probably never be as this is a very fragile feature.

**Comment by oawang** [comment]
Is there another solution?

**Comment by oawang** [comment]
> domain names in route statements are not supported in openvpn3 and will probably never be as this is a very fragile feature.

Is there another solution?
