### ISSUE TITLE
Missing native arm64 (Apple Silicon - M1) support

### ISSUE THREAD

**Issue by apps4everyone** [OpenVPN/openvpn3#194]
Missing native arm64 (Apple Silicon - M1) support. 

Currently Open VPN Connect Mac App is running in Rosetta 2 mode. (x86_x64)

**Comment by schwabe** [comment]
This a repository for the Library, it supports ARM just fine. For the OpenVPN Connect client [https://openvpn.net/vpn-server-resources/support-options-for-openvpn/](please contact suppport).

**Comment by apps4everyone** [comment]
but does it support arm64 for macOS? only see x86_64 in the build scripts for macOS.

**Comment by apps4everyone** [comment]
I think arm64 is only for iOS/iPadOS...

**Comment by schwabe** [comment]
@apps4everyone those scripts are not preferred way to build openvpn3 anymore and [OpenVPN3 for Linux](https://github.com/OpenVPN/openvpn3-linux) and the test binaries built by cmake (ovpncli) on macOS support arm64 just fine. Just as datapoint for you:

```
[11:13]arne@styx:~%  ~/tmp/ut/core/test/ovpncli/ovpnclinull --version
OpenVPN cli 1.0
OpenVPN core 3.7_git:master mac arm64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.
```

**Comment by apps4everyone** [comment]
thx for the info, maybe the readme is misleading:
https://github.com/OpenVPN/openvpn3#building-the-openvpn-3-client-on-mac-os-x
