### ISSUE TITLE
MacOS 11.6.2 (20G314) Build Library Failed

### ISSUE THREAD

**Issue by mYCBS** [OpenVPN/openvpn3#196]
![image](https://user-images.githubusercontent.com/11468900/152981127-21871409-bda9-4a56-bcd8-eaa2a939a4cc.png)

openVPN3 build Error on Mac，like this ,Anyone can help? THANKS

**Comment by mYCBS** [comment]
cmake --build .    command Error,Already Try many ways,someone can help?

**Comment by mYCBS** [comment]
> Which mbed TLS version are you building against? Is there a strict requirement for mbed TLS, or can OpenSSL be an alternative. Performance and TLS-protocol feature wise, OpenSSL is a much better option these days.


Thanks for the answer; I am currently compiling with mbed tls 3.1.0, which is larger than the required version;
I don't know if the dependency is not established successfully, so that the corresponding function cannot be found.

**Comment by dsommers** [comment]
IIRC, Mbed TLS 3.x might be too new.  We are not having too much focus on the mbed TLS support, as OpenSSL gives far better performance across all platforms and generally works better for our users.  Try the latest mbed TLS 2.x version and see if that works better.

**Comment by mYCBS** [comment]
> IIRC, Mbed TLS 3.x might be too new. We are not having too much focus on the mbed TLS support, as OpenSSL gives far better performance across all platforms and generally works better for our users. Try the latest mbed TLS 2.x version and see if that builds better.

I re-downloaded and compiled mbed tls2.7.5, and then used the tar command to compress it into gz format, but still reported the same error

**Comment by mYCBS** [comment]
> IIRC, Mbed TLS 3.x might be too new. We are not having too much focus on the mbed TLS support, as OpenSSL gives far better performance across all platforms and generally works better for our users. Try the latest mbed TLS 2.x version and see if that builds better.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/11468900/153320970-97f71ffa-0209-40fe-85f6-81c1d990c4b0.png">
How to rely on openssl to compile on mac?

**Comment by mYCBS** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/11468900/153361206-a8d8f029-ab10-4527-b81d-19d01a99ac01.png">
The openssl dependency has been modified, but this error is reported after the compilation is completed, which is a bit confusing

**Comment by mYCBS** [comment]
> I updated the macos build instructions in the README.rst. Can you follow those instruction?

Thanks, there are some problems with my computer environment, and the compilation is successful on other computers;
But there is still a question. After the compilation is successful, how should openvpn3 be introduced into the Xcode project for use? Can you complete some introduction steps?

**Comment by schwabe** [comment]
Closing the issue since the problem is solved. As for Xcode, currently no one of us uses Xcode to develop, so no idea about that, sorry.
