### ISSUE TITLE
build on osx with asio error

### ISSUE THREAD

**Issue by starup** [OpenVPN/openvpn3#2]
hi, i am build openvpn3 on osx, but occurs the flowing asio erros：

~/src/ovpn3/core/openvpn/buffer/buffer.hpp:387:11: error: no type named
      'mutable_buffers_1' in namespace 'asio'; did you mean 'mutable_buffer'?
    asio::mutable_buffers_1 mutable_buffers_1(const size_t tailroom = 0)

~/src/ovpn3/core/openvpn/buffer/buffer.hpp:394:11: error: no type named
      'mutable_buffers_1' in namespace 'asio'; did you mean 'mutable_buffer'?
    asio::mutable_buffers_1 mutable_buffers_1_append(const size_t tailroom = 0)

anyone can help me ?

**Comment by starup** [comment]
solved，just undef ASIO_NO_DEPRECATED。

**Comment by amhed** [comment]
I'm getting a similar error. What was the solution?
