### ISSUE TITLE
error of "cannot acquire TAP handle"

### ISSUE THREAD

**Issue by candylife9** [OpenVPN/openvpn3#201]
I fetch the openvpn3 source package and construct it in visual studio, and generate the cli.exe from openvpn3/test/ovpncli/cli.cpp. Then I create the cli.ovpn , and start cli.exe with this cli.ovpn. It just gives an error of following:
`Fri Mar 11 15:15:21 2022 TAP ADAPTERS:

Open TAP device "" PATH="" FAILED
Fri Mar 11 15:15:21 2022 TUN Error: cannot acquire TAP handle
Fri Mar 11 15:15:21 2022 EVENT: TUN_IFACE_CREATE cannot acquire TAP handle [FATAL-ERR]
Fri Mar 11 15:15:21 2022 EVENT: DISCONNECTED
Fri Mar 11 15:15:21 2022 Client exception in transport_recv: tun_exception: not connected
Thread finished`

but I use the OpenVPN Connect installer for windows , and connect to the server with the same cli.ovpn, it works well. So, is there anything wrong with my cli.exe ? Anything extra or callbacks needs to be done with openvpn3 client ?

**Comment by lstipakov** [comment]
OpenVPN Connect is a proprietary software and uses different hardware id for its tap-windows6 driver. For opensource software like openvpn2 and openvpn3 you need a tap-windows6 driver from OpenVPN Community client (https://openvpn.net/community-downloads/).

**Comment by candylife9** [comment]
> OpenVPN Connect is a proprietary software and uses different hardware id for its tap-windows6 driver. For opensource software like openvpn2 and openvpn3 you need a tap-windows6 driver from OpenVPN Community client (https://openvpn.net/community-downloads/).

Yes, I remove the OpenVPN Connect and its tap-windows driver ,and re-download the OpenVPN-2.5.5-I602-amd64. Then everything is okay. Even though I don't kown what's the distinguish between OpenVPN Connect and opensource software, but you really helped me. Thanks a lot ^-^
