### ISSUE TITLE
Openwrt

### ISSUE THREAD

**Issue by predators46** [OpenVPN/openvpn3#205]
can you add for openwrt?

**Comment by dsommers** [comment]
Just so we have a better understanding: What is it you expect from OpenVPN 3 on OpenWRT which the current OpenVPN 2.x code base does not provide?

Currently, we only have open source code available to run OpenVPN client connections based off OpenVPN 3.  It is also written in C++, which will require a bit more runtime memory and it pulls in C++ libraries.  As OpenWRT targets embedded devices often with more scarce resources, OpenVPN 3 might not be then most ideal solution to OpenWRT. The reference OpenVPN 3 client is roughly twice as big as the OpenVPN 2.x builds, when all debug details are stripped from the binary - and it only provides client features.

**Comment by openwrtfirmwarecostum** [comment]
I need SNI in openvpn3

**Comment by dsommers** [comment]
@openwrtfirmwarecostum OpenVPN does not rely on SNI for the connection itself.

The `--verify-x509-name` option may be of useful to verify the certificate subject.  There are also server mode script hooks in OpenVPN 2.x which will allow you to extract client certificate details for evaluation and authentication.

The value of SNI support is unclear.
