### ISSUE TITLE
autoload does not establish connection

### ISSUE THREAD

**Issue by SomaGallai** [OpenVPN/openvpn3#207]
Hi,

I have been trying to setup the [autoload](https://openvpn.net/blog/openvpn-3-linux-and-auth-user-pass/) following the guide. 

The issue is that `openvpn3 sessions-list` gives the following output:

``` bash
-----------------------------------------------------------------------------
        Path: /net/openvpn/v3/sessions/0000000000000
     Created: Thu Apr  7 15:15:27 2022                  PID: 0000
       Owner: name                                   Device: 
 Config name: client.ovpn
      Status: Web authentication required to connect
-----------------------------------------------------------------------------
```
Why does it require Web authentication, I thought the point is to skip that step.

Using `openvpn3 session-start --config client.ovpn` it works as expected, opens a browser page where I have to login and the connection is authorized properly. I have made sure that the `client.autoload` file is set up with the correct credentials following the guide structure:

``` bash
{
    "autostart": true,
    "user-auth": {
        "autologin": true,
        "username": "jane.doe",
        "password": "very-secret-Let-Me-!n-P4ssword"
    }
}
```

**Comment by SomaGallai** [comment]
Closing as the [openvpn3-linux](https://github.com/OpenVPN/openvpn3-linux) repository is more suitable for the issue.

**Comment by dsommers** [comment]
This is tracked in openvpn3-linux [issue #119](https://github.com/OpenVPN/openvpn3-linux/issues/119)
