### ISSUE TITLE
peer-id handle error？

### ISSUE THREAD

**Issue by orientlu** [OpenVPN/openvpn3#210]
![企业微信截图_16510714811589](https://user-images.githubusercontent.com/6871867/165658794-793edd79-cd0d-4a85-b8dd-263da9745f72.png)

<img width="800" alt="af858319-6db5-4ef2-9abe-32c7cb99eeaa" src="https://user-images.githubusercontent.com/6871867/165658818-ea6ceeec-060a-4816-99fb-21ad8e74c4a0.png">

int?

**Comment by dsommers** [comment]
At first quick glance, this looks correct.  The Peer ID field in the OpenVPN wire protocol is designed to be 24 bit.  I don't recall now why `0xffffff` is excluded, but I have some vague memories that value has a special meaning on the server side and clients should never see this value.

Which server are you connecting to?

**Comment by orientlu** [comment]
the version of server is 2.4.8, and the client is 3.3.3;
but it work on udp tunnel mode

**Comment by orientlu** [comment]
server push peer-id = 0xffffff  to client  when --float disable?

**Comment by lstipakov** [comment]
I wonder how you managed to get such peer-id value from the server. Could you paste your config (excluding private parts)?

**Comment by orientlu** [comment]
`client
dev tun
proto udp
remote 10.19.19.1 30000
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert vpngwSslClient-4awvhm2c.crt
key vpngwSslClient-4awvhm2c.key
remote-cert-tls server
cipher none
auth none
verb 3

#ignore-unknown-option data-ciphers compat-mode
compat-mode 2.4.8
`

**Comment by orientlu** [comment]
`port 30000
proto tcp
dev tun
server-id 11
ca ca.crt
crl-verify crl.pem
cert 109.crt
key 109.key
dh dh.pem

cipher none
opt-verify
ncp-disable
auth none
max-clients 1500
rcvbuf 67108864

push "route 172.19.19.0 255.255.255.0"

server 192.168.19.0 255.255.255.0
topology subnet

keepalive 2 10
log-append ./openvpn.log
verb 5
replay-window 1500

script-security 2

up ../bin/openvpn-tunup.sh
client-connect ../bin/client-connect.sh
client-disconnect ../bin/client-disconnect.sh
check-client-cn-pre ../bin/init-check-client-cn.sh
check-client-cn ../bin/check-client-cn.sh

disable-preempt
management /var/run/109-management-0.sock unix
`

**Comment by dsommers** [comment]
This server seems to be quite patched .... there are several options(`check-client-cn`, `check-client-cn-pre`, `disable-preempt`)  here which does not exist in upstream OpenVPN releases.  Can you try to run this on an upstream release of OpenVPN and not one you patched?

And also, please share your server source code.

**Comment by orientlu** [comment]
there are several options(check-client-cn, check-client-cn-pre, disable-preempt) are add by openvpn_run_script to make some limit when client connect
and i found when tcp mode,. server send peer-id = 0xffffff mean disable float. but is seam that  client did not get it

**Comment by lstipakov** [comment]
Server is supposed to send "peer-id: -1" in PUSH_REPLY string in order to disable peer-id. May I ask why you want to disable it?

**Comment by orientlu** [comment]
i do not want to disable
but client throw error when rev peer-id=-1

**Comment by schwabe** [comment]
@orientlu What you are running as server is NOT OpenVPN. It is some fork/patched version of OpenVPN that is incompatible with normal OpenVPN clients. So we have no idea what your server is doing and why. We only know that it behaves different here.

**Comment by dsommers** [comment]
@orientlu I suspect your patched OpenVPN server is not handling peer-id as a 24bit signed value, but a 32 or 64 bit signed value.

24bit: 0xffffff = -1
32/64bit: 0x00ffffff = 16777215

For us to confirm this, you need to share your server code.

**Comment by orientlu** [comment]
![image](https://user-images.githubusercontent.com/6871867/165923653-27122b46-ed72-4914-b675-df75847b7c84.png)

i found the only different is here

**Comment by schwabe** [comment]
@orientlu please share the whole source code. At least I am not going to debug your custom version without you respecting the GPL in spirit (and not only in letter).

But that comments look like your changes assign an invalid value on purpose and then invalid value is leaking to the push message, so basically your changes are wrong and break the protocol. So basically it is your own problem with your own modifications.

**Comment by orientlu** [comment]
@schwabe :) i fork but not commit my modify yet.
only add a peer-id default value make me cray hold day ,,.,
