### ISSUE TITLE
The difference between openvpn3 and openvpn2.x

### ISSUE THREAD

**Issue by vazyme** [OpenVPN/openvpn3#214]
OpenVPN 3 is a C++ class library that implements the functionality of an OpenVPN client。

Did I understand it wrong? I just saw openvpn3 and thought it was the dll provided by openvpn. After the compilation was completed, ovpncli.exe was generated. No dll/lib compiled, very disappointed.
I am new to openvpn3 and don't know much about it. I would like to ask, are openvpn3 and openvpn2.x only the difference between C and C++?
And does openvpn provide dll? , I can call the interface directly.

**Comment by schwabe** [comment]
You certainly can build openvpn3 into a standalone library. For example https://github.com/schwabe/ics-openvpn uses openvpn3 as .so library using the swig/java interface. The demo client (ovpncli) you saw instead directly compiles/bundles it. There is no technical reason against building a dll library but it is not something it is provided out of the box unless you use the swig interface (search ovpncli.i in the repo).
