### ISSUE TITLE
openvpn3 features

### ISSUE THREAD

**Issue by yxungh** [OpenVPN/openvpn3#216]
HI
I am going to use the openvpn3 client to embed into my project. I am currently using the openvpn2.x/openvpn-gui client. Can I transition to openvpn3? Or does openvpn3 have the full functionality of an openvpn2 client?
Just getting started with openvpn3, asking for help, thanks a lot.

**Comment by schwabe** [comment]
OpenVPN3 has not the full functionality of the openvpn2 client. It also has a different license. You will probably open source your whole project if you use openvpn3. Unless you need to use OpenVPN3 for a specific reason, there is no compelling reason to switch to OpenVPN3 either.
