### ISSUE TITLE
openvpn3 supports wintun

### ISSUE THREAD

**Issue by vazyme** [OpenVPN/openvpn3#217]
HI
In openvpn2.x, SYSTEM authority is required to use wintun driver. I found that openvpn3 does not implement OpenVPNServiceInteractive, but why can it support wintun?
Thanks in advance

**Comment by lstipakov** [comment]
You need to use openvpn agent, which is openvpn3 equivalent of OpenVPNServiceInteractive.

To try it out;

 - Download latest build artifacts, for example https://github.com/OpenVPN/openvpn3/suites/6374869439/artifacts/231032114
 and unzip to, say, `c:\Temp\openvpn\`
 - create registry key `omi_exe_path` at `HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN` with empty value (it just have to be there, currently not used)
 - run in admin command prompt:
  `c:\Temp\openvpn\openvpn\ovpnagent\win>ovpnagent.exe run`
 - run in (non-admin) command prompt:
  `c:\Temp\openvpn\test\ovpncli>ovpncliagent.exe -w c:\Users\lev\vpns\example.ovpn`

**Comment by lstipakov** [comment]
While openvpn3 agent code does impersonation as SYSTEM, you are supposed to run it as a system service.

**Comment by vazyme** [comment]
@lstipakov 
Thanks for the guidance, I found that (example.ovpn) is different from openvpn2.X, but I can't find any example about openvpn3 config file, can you provide me?

**Comment by vazyme** [comment]
I didn't understand openvpn3 so quickly, but I wanted to test it first.

**Comment by lstipakov** [comment]
Just feed it openvpn2 config, it will ignore unknown options.

**Comment by vazyme** [comment]
@lstipakov 
ok, thank you for running the test program, but when I compare the openvpn2-gui2.5.5 client, I also use wintun and the same server. Why does the performance seem to be different?
Test with iperf3:
openvpn3 : 340M
openvpn2 : 460M

**Comment by lstipakov** [comment]
I don't know - not enough data to analyze.

**Comment by vazyme** [comment]
ok,thank you very much

**Comment by vazyme** [comment]
@lstipakov 
Thanks, I learned about 2.6git you said, it seems that the encryption is transferred to the kernel, but it has not been released yet, is it stable now? Is there a release plan?
