### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by supreethkm** [OpenVPN/openvpn3#22]
HI I created build this Linux ARM, app is crashing at pthread.join(), Can anyone help me to resolve this?

**Comment by dsommers** [comment]
This isn't a support forum.  Please provide details of what is happening, debug backtraces, pointers to source code where things crash, etc ... something which provides enough information to understand what you are trying to do.

**Comment by supreethkm** [comment]
I'm developing a oven vpn client for Tizen (samsung OS- linux arm) ,mobile platform,  I have used tunnel builder for tunnel creation, Tunel establish should happen from user access through popup. Some time's its connecting and sometimes not. Every time its crashing at pthread_join().

**Comment by dsommers** [comment]
We need to see some backtraces and preferably also some of your code to be able to understand what is happening.  Please also have a look at the reference implementation of a client in test/ovpncli/cli.cpp.

Btw, I am currently working on a Linux client implementing OpenVPN 3.  I don't know Tizen (I know the history of how MeeGo ended up as Tizen and before that), but it might be you can facilitate some of the backend work we're doing there.  The implementation I'm working on makes use of D-Bus and lets unprivileged users start and manage OpenVPN VPN tunnel, most of it is facilitated using the auto-start feature of D-Bus, so if no tunnel is started - there is zero overhead on the system/device.  This Linux client is planned to be GPLv3 licensed.  I hope that I soon will have everything in a stable enough shape to publish a git repository with it.

**Comment by dsommers** [comment]
Closing it as there are no backtraces to study.
