### ISSUE TITLE
myip.opendns .com

### ISSUE THREAD

**Issue by vazyme** [OpenVPN/openvpn3#221]
HI!
When I run openvpn3, my environment seems to have detected that myip.opendns .com has been accessed and considered it to be a threat. Under what circumstances will this address be accessed? Is there a way to avoid it?

**Comment by dsommers** [comment]
You need to provide much more details for this to make any sense.

* Which OS are you running?
* Which exact OpenVPN client are you running?
* Which VPN server/service are you connecting to?
* Where does this threat warning appear?

**Comment by vazyme** [comment]
1. run on windows system
2. Relying on openvpn3 simply inherits OpenVPNClient, does not rewrite any virtual functions, and does not use openvpnagent
3. openvpnGUI is running and not connected
4. The alert was intercepted by my own firewall, showing ET POLICY External IP Lookup Domain (myip.opendns .com in DNS lookup)

**Comment by vazyme** [comment]
@ordex Thanks, it is possible
I just want to confirm to you if openvpn3 is called, and I didn't find it in the code myself.

I still have another doubt. I remember the openvpnagent I used yesterday, and this did not happen. Is there any difference between using the agent or not? I don't know much about code yet

**Comment by lstipakov** [comment]
Without agent you need to run openvpn as elevated process, because configuring network adapter requires administrative privileges. Agent is a separate process which runs as privileged (usually as a windows service) and takes care of setting up network. This allows you to run openvpn without elevation.
