### ISSUE TITLE
Unable to Create a OpenVPN Session (Custom Client Implementation)

### ISSUE THREAD

**Issue by OPstriker** [OpenVPN/openvpn3#228]
Platform : Windows

Error:
```
The thread 0x2d38 has exited with code 0 (0x0).
Exception thrown at 0x00007FF986AE474C in LYCF.exe: Microsoft C++ exception: openvpn::ErrorCode at memory location 0x000000C34BBD79A0.
Exception thrown at 0x00007FF986AE474C in LYCF.exe: Microsoft C++ exception: openvpn::ClientProto::Session::tun_exception at memory location 0x000000C34BBDA230.
The thread 0x9f0 has exited with code 0 (0x0).
```

My Implementation (Please Correct me if I'm Wrong....): 
VPN_H: 
```
#pragma once
#include <ovpncli.hpp>

#include "LYCF.h"

namespace v0iden
{
	class VPN
	{
	public:
		static void v_connect();

	};
};
```

vpn.cpp:
```
#include "vpn.h"

using namespace openvpn;
class Client : public ClientAPI::OpenVPNClient
{
private:

	virtual void event(const ClientAPI::Event& ev) override {

	}

	virtual void log(const ClientAPI::LogInfo& loginf) override {

	}

	virtual void external_pki_cert_request(ClientAPI::ExternalPKICertRequest& certreq) override {

	}

	virtual void external_pki_sign_request(ClientAPI::ExternalPKISignRequest& signreq) override {

	}

	virtual bool pause_on_connection_timeout() override {
		return false;
	}

	bool socket_protect(int socket, std::string remote, bool ipv6) override
	{
		return true;
	}

};



void v0iden::VPN::v_connect()
{

	LYCF::VPN_LYCF::vpnstat = false;

	using namespace openvpn::ClientAPI;

	ClientAPI::Config config;

	MergeConfig mc;

	mc = OpenVPNClientHelper::merge_config("C:\\Users\\skill\\Desktop\\Experiments\\LYCF - DirectX\\LYCF\\Build\\x64\\Release\\profiles\\OPstriker.ovpn", true); // fuck, i forgot to exclude this lmao, now you know my path...

	config.content = mc.profileContent;
	config.autologinSessions = true;
	config.allowLocalDnsResolvers = true;
	config.tunPersist = true;

	Client client;

	ClientAPI::EvalConfig eval = client.eval_config(config);

	ClientAPI::Status status = client.connect();

	if (status.error)
		LYCF::VPN_LYCF::vpnstat = false;

}
```

**Comment by OPstriker** [comment]
Did some extra Debugging and found this issue,
```
TAP ADAPTERS:

Open TAP device "" PATH="" FAILED
TUN Error: cannot acquire TAP handle
ERROR: TUN_IFACE_CREATE
Client exception in transport_recv: tun_exception: not connected

```

**Comment by OPstriker** [comment]
Let me Clarify that I have the Drivers installed, but I'm still able to establish an connection....
![image](https://user-images.githubusercontent.com/76495154/177429704-b52f6913-3d9c-4574-8fc0-2ba7994b4924.png)

**Comment by schwabe** [comment]
Try using the small demo client ovpncli.exe first and see if that works before trying to build your own client.

**Comment by OPstriker** [comment]
Ahh, finally got a reply lol, and yes I did tryout the CLI version first and It worked without any issues. Except when I tried to implement it on my own App, I get the error :

> Did some extra Debugging and found this issue,
> 
> ```
> TAP ADAPTERS:
> 
> Open TAP device "" PATH="" FAILED
> TUN Error: cannot acquire TAP handle
> ERROR: TUN_IFACE_CREATE
> Client exception in transport_recv: tun_exception: not connected
> ```

**Comment by OPstriker** [comment]
ok, somehow WinTun works

**Comment by OPstriker** [comment]
but i have no luck with the Tap Adapter

**Comment by OPstriker** [comment]
i'll close this now....

**Comment by OPstriker** [comment]
Closed, it Early But I managed to get the Tap Adapter working by adding `TAP_WIN_COMPONENT_ID=tap0901` to the preprocessor definitions...

**Comment by mrizkihidayat66** [comment]
Hi, were you able to solve this issue? I’m facing a similar problem with the following details:
```
Exception thrown at 0x757C0F22 in Client.exe: Microsoft C++ exception: openvpn::ErrorCode at memory location 0x0BCBCA0C.
Exception thrown at 0x757C0F22 in Client.exe: Microsoft C++ exception: openvpn::ClientProto::Session::tun_exception at memory location 0x0BCBD6E0.
```

I’m not sure what’s causing this issue in my custom client. Could you provide more details about your experience with:
> ok, somehow WinTun works but I have no luck with the Tap Adapter..., well, I guess something works... lol

Any insights would be greatly appreciated. Thanks!

**Comment by OPstriker** [comment]
> Hi, were you able to solve this issue? I’m facing a similar problem with the following details:
> 
> ```
> Exception thrown at 0x757C0F22 in Client.exe: Microsoft C++ exception: openvpn::ErrorCode at memory location 0x0BCBCA0C.
> Exception thrown at 0x757C0F22 in Client.exe: Microsoft C++ exception: openvpn::ClientProto::Session::tun_exception at memory location 0x0BCBD6E0.
> ```
> 
> I’m not sure what’s causing this issue in my custom client. Could you provide more details about your experience with:
> 
> > ok, somehow WinTun works but I have no luck with the Tap Adapter..., well, I guess something works... lol
> 
> Any insights would be greatly appreciated. Thanks!

from my understanding, this has to be an issue with OpenVPN's inability to create the tunnel. I have since stopped working on this project, but you need more information to debug the issue. I would log out everything from `LogInfo` which provides more details on the issue.

```
	virtual void log(const ClientAPI::LogInfo& loginf) override {
            std::cout << "[" << date_time() << "] " << info.text << std::flush;
	}
```
Hope this helps @mrizkihidayat66

**Comment by OPstriker** [comment]
> Closed it Early But I managed to get the Tap Adapter working by adding `TAP_WIN_COMPONENT_ID=tap0901` to the preprocessor definitions...

Do you have `tap0901` defined and the drivers installed for Tap driver?

**Comment by mrizkihidayat66** [comment]
> Do you have `tap0901` defined and the drivers installed for Tap network interface?

Yes, I have defined it. But does this mean my custom client isn't using the correct adapter like ovpncli does? When I run the original, unmodified ovpncli code, it works fine. However, the code that I ported, refactored, and added some callbacks to is giving this error.

**Comment by OPstriker** [comment]
> > Do you have `tap0901` defined and the drivers installed for Tap network interface?
> 
> Yes, I have defined it. But does this mean my custom client isn't using the correct adapter like ovpncli does? When I run the original, unmodified ovpncli code, it works fine. However, the code that I ported, refactored, and added some callbacks to is giving this error.

Also, this could be an issue with privileges on Windows. Try running the client with Admin permissions, since you need elevation to create Tun Adapters. This is why OpenVPN uses `ovpnagent` which runs in the background with admin's perms and handles the creation of adapters and managing them.

**Comment by mrizkihidayat66** [comment]
> Also, this could be an issue with privileges on Windows. Try running the client with Admin permissions, since you need elevation to create Tun Adapters. This is why OpenVPN uses `ovpnagent` which runs in the background with admin's perms and handles the creation of adapters and managing them.

Ah, I think a driver is missing. When I tried ovpncli again, it had the same problem as my custom client. I remember installing OpenVPN-2.6.13-I002-amd64.msi yesterday and then uninstalling it. Maybe the driver was removed as well since I used Revo Uninstaller. I'll investigate this further and provide an update later. Thank you!
