### ISSUE TITLE
connect error: Missing External PKI alias. 

### ISSUE THREAD

**Issue by pavel-piskun** [OpenVPN/openvpn3#23]
I've got '**connect error: Missing External PKI alias**' with this client on Ubuntu 16.04

**Comment by ordex** [comment]
Sorry, but this is not a bug.
You are probably not providing the library with all the needed information.
If you need help in using the OpenVPN3 core library I'd suggest you to write to the OpenVPN mailing list.

Also, ensure you mention the used configuration, your setup and how you have implemented the client.
