### ISSUE TITLE
How to build openvpn3 on iOS?

### ISSUE THREAD

**Issue by RanchenY** [OpenVPN/openvpn3#25]
Hello,
How to build openvpn3 to iOS? thanks

**Comment by dsommers** [comment]
This openvpn3 project is not a full fledged client by itself.  It is OpenVPN as a library, so you need to implement this library into your own iOS client.

**Comment by RanchenY** [comment]
OK. Thank you for your reminding. I think I solved it. I don't know if that's right.....
