### ISSUE TITLE
openvpn3 on macos cannot set scoped dns correctly

### ISSUE THREAD

**Issue by zeddit** [OpenVPN/openvpn3#254]
When using openvpn access server, it could set split tunnels (DNS resolution zones) which resolve some specific domains so that change the direction of the traffic.

Concretely, the server will push some dns resolvers and the macOS will set up some scoped dns queries to achieve that.

However, openvpn3 client cannot setup the scoped dns correctly, while the tunnelblick client could. 
The png below shows the dns resolver of tunnelblick from command `scutil --dns`, the scoped dns queries are correct.
https://imgloc.com/i/njPUw

However, openvpn3 doesn't set up any scoped dns but set normal resolver with **supplymentary** flag, which doesn't work if the main resolver can grab the same domain from the public network.

Is it a bug or future feature for openvpn3?

**Comment by schwabe** [comment]
You are reporting an issue for OpenVPN Connect, the commerical offering of OpenVPN Inc. The OpenVPN Connect team does not want issues reported via Github but rather report them via https://support.openvpn.net/. Please use that website if you want to report an issue with OpenVPN Connect or have any other issue with that application.

**Comment by zeddit** [comment]
I'am not reporting an issue for OpenVPN Connect, but the command line software openvpn3 working as client mode.
By importing the same ovpn config file. The tunnelblick worked as expected while openvpn3 working in client mode not.

**Comment by schwabe** [comment]
The command line client is jus a demo app. And things like setting up DNS and other platform specific only have basic implementations in the openvpn3 library and are thought to be part of the actual client implementation like Connect or another client. While we certainly welcome contributions that improve the openvpn3 library implementation, the library implementation is not expected to provide more than basic functionality.
