### ISSUE TITLE
Option "pull-filter", "push" ignored on Android App

### ISSUE THREAD

**Issue by kilroy98** [OpenVPN/openvpn3#255]
I use this options in my client config and app ignore it
```
pull-filter ignore "dhcp-option DNS 77.88.8.8"
pull-filter ignore "route 77.88.8.8"
pull-filter ignore "dhcp-option DNS 77.88.8.1"
pull-filter ignore "route 77.88.8.1"
push "dhcp-option DNS 1.1.1.1"
push "route 1.1.1.1"
push "dhcp-option DNS 8.8.8.8"
push "route 8.8.8.8"
```
Android 12 (MIUI 13), OpenVPN App Version - 3.3.0 (subscribed to beta updates).

And ignores this options:
```
nobind
setenv opt ncp-ciphers AES-128-GCM:AES-128-CBC:AES-256-GCM:AES-256-CBC
```

**Comment by cron2** [comment]
Hi,

On Wed, Jan 11, 2023 at 11:54:13AM -0800, Dmitriy wrote:
> I use this options in my client config and app ignore it
> ```
> pull-filter ignore "dhcp-option DNS 77.88.8.8"
> pull-filter ignore "route 77.88.8.8"
> pull-filter ignore "dhcp-option DNS 77.88.8.1"
> pull-filter ignore "route 77.88.8.1"
> push "dhcp-option DNS 1.1.1.1"
> push "route 1.1.1.1"
> push "dhcp-option DNS 8.8.8.8"
> push "route 8.8.8.8"
> ```

push is a server-side option.

If you want this on the client, just set the options directly:

```
dhcp-option DNS 1.1.1.1
route 1.1.1.1
dhcp-option DNS 8.8.8.8
route 8.8.8.8
```

> Android 12 (MIUI 13), OpenVPN App Version - 3.3.0 (subscribed to beta updates).
> 
> And ignores this options:
> ```
> nobind
> setenv opt ncp-ciphers AES-128-GCM:AES-128-CBC:AES-256-GCM:AES-256-CBC
> ```

Just leave them out.  nobind is default, and ncp-ciphers is only rarely
needed.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by kilroy98** [comment]
But why then in Windows and my router in the logs there are no warnings that these commands are ignored?
And what about pull-filter commands?

**Comment by schwabe** [comment]
If you look at an app with current OpenVPN3 version like OpenVPN for Android, you will see that you get warnings for these options being ignored. 

If you want to raise a bug with OpenVPN Connect, please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.
