### ISSUE TITLE
DNS doesn't resolve after Reconnect.

### ISSUE THREAD

**Issue by OPstriker** [OpenVPN/openvpn3#257]
**OS: Windows 11 (22H2)
Arch: amd64
dco-ver: 0.8.3**

I'm not sure if anyone else can reproduce this issue, but on the first initial connect i am able to successfully connect, but after trying to reconnect by `the_client->stop();` then `ClientAPI::Status status = client.connect();`. I can no longer resolve DNS and can only connect to sites with IPv4 (eg. 1.1.1.1). This issue seems oddly new and I'm not sure whether it's on my side or in the library. But After I kill my application I can resolve DNS again.

**log:** 
```
[Sun Jan  1 22:38:02 2023] OpenVPN core 3.8_git:master win x86_64 64-bit OVPN-DCO
[Sun Jan  1 22:38:02 2023] Frame=512/2112/512 mssfix-ctrl=1250
[Sun Jan  1 22:38:02 2023] NOTE: This configuration contains options that were not used:
[Sun Jan  1 22:38:02 2023] Unsupported option (ignored)
[Sun Jan  1 22:38:02 2023] 4 [resolv-retry] [infinite]
[Sun Jan  1 22:38:02 2023] 11 [auth-nocache]
```
Then after a bit resolv-retry kicks-in:
```
[Sun Jan  1 22:51:53 2023] Server poll timeout, trying next remote entry...
[Sun Jan  1 22:51:55 2023] Transport Error: DNS resolve error on 'example.com' for TCP session: No such host is known.
[Sun Jan  1 22:51:55 2023] Client terminated, restarting in 2000 ms...
```

**Comment by lstipakov** [comment]
@OPstriker I think [this](https://github.com/lstipakov/openvpn3/commit/d3471dba6f8fd3a72d055647d77963f2cc2fba2e) should fix it. Could you give it a try?

**Comment by lstipakov** [comment]
The first fix didn't cover the case of `persist-tun` and changed options. Here is a [new](https://github.com/lstipakov/openvpn3/commit/3f1f6826a70ff7ca43dd4eb8ce84693517b53887) one.

**Comment by OPstriker** [comment]
> @OPstriker I think [this](https://github.com/lstipakov/openvpn3/commit/d3471dba6f8fd3a72d055647d77963f2cc2fba2e) should fix it. Could you give it a try?

@lstipakov, It now works!!!, ty!

closing since resolved...
