### ISSUE TITLE
Transport Error: socket_protect error (TCPv4)

### ISSUE THREAD

**Issue by mane** [OpenVPN/openvpn3#258]
Hi,

I am having an issue using the openvpn client on:

OS:  MacOS 13.1
CPU: Apple M1 Max
Openvpn client: 3.4.1 (4522)

The error messages on the logs are:

24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock
{
	"host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF
	"ipv6" : false,
	"pid" : 1578
}

⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4)
⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...

Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:

sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent

I hope this issue can be addressed and fixed.

Happy to provide more details if needed.

Thank you!

**Comment by schwabe** [comment]
Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.

**Comment by Matrix7867** [comment]
> Hi,
> 
> I am having an issue using the openvpn client on:
> 
> OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> 
> The error messages on the logs are:
> 
> 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> 
> ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> 
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> 
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> 
> I hope this issue can be addressed and fixed.
> 
> Happy to provide more details if needed.
> 
> Thank you!

One of my teammate was having the same issue and executed your command. It got fixed!! 👍

**Comment by nashihu** [comment]
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent

thank you very much, this still happens in openvpn 2024. your comment helps a lot

**Comment by evanwangace** [comment]
> Hi,
> 
> I am having an issue using the openvpn client on:
> 
> OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> 
> The error messages on the logs are:
> 
> 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> 
> ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> 
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> 
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> 
> I hope this issue can be addressed and fixed.
> 
> Happy to provide more details if needed.
> 
> Thank you!

Your command is very useful, I have fixed it by your command, thank you very much!

**Comment by Alireza1999** [comment]
> Hi,
> 
> I am having an issue using the openvpn client on:
> 
> OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> 
> The error messages on the logs are:
> 
> 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> 
> ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> 
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> 
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> 
> I hope this issue can be addressed and fixed.
> 
> Happy to provide more details if needed.
> 
> Thank you!

Ahhhh 
Thank you man
you saved my life <3

**Comment by xhatt** [comment]
> > Hi,
> > I am having an issue using the openvpn client on:
> > OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> > The error messages on the logs are:
> > 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> > ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> > Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> > sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> > I hope this issue can be addressed and fixed.
> > Happy to provide more details if needed.
> > Thank you!
> 
> Ahhhh Thank you man you saved my life <3

The issue occurred because the OpenVPN app was unable to successfully start the Agent process when it launched. The previously mentioned command needs to be run each time to start the app. Today, I found a solution: go to Settings > General > Login Items, then find OpenVPN Client under "Allow in Background" and toggle the switch on.

This passage was translated from Chinese by AI, and the wording may not be accurate.

**Comment by jebraili** [comment]
> Hi,
> 
> I am having an issue using the openvpn client on:
> 
> OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> 
> The error messages on the logs are:
> 
> 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> 
> ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> 
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> 
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> 
> I hope this issue can be addressed and fixed.
> 
> Happy to provide more details if needed.
> 
> Thank you!

Thanks so much,You save me.

**Comment by mitchellkolk** [comment]
> Hi,
> 
> I am having an issue using the openvpn client on:
> 
> OS: MacOS 13.1 CPU: Apple M1 Max Openvpn client: 3.4.1 (4522)
> 
> The error messages on the logs are:
> 
> 24, 2023, 11:04:30] EVENT: WAIT ⏎[Jan 24, 2023, 11:04:30] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock { "host" : "XX.XX.XX.XX", <---- MASKED BY MYSELF "ipv6" : false, "pid" : 1578 }
> 
> ⏎[Jan 24, 2023, 11:04:30] Transport Error: socket_protect error (TCPv4) ⏎[Jan 24, 2023, 11:04:30] Client terminated, restarting in 2000 ms...
> 
> Apparently the issue is due to the openvpn agent not starting with the client and a workaround is the following:
> 
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
> 
> I hope this issue can be addressed and fixed.
> 
> Happy to provide more details if needed.
> 
> Thank you!

Thanks! This solved my issue too. I keept reinstalling the damn VPN. This works better.

**Comment by cron2** [comment]
This issue is **closed** and also **off-topic** (Connect issues are not dealt with in GH issues).  So why are you posting here?
