### ISSUE TITLE
Avoid overriding system-managed DNS resolver on Windows?

### ISSUE THREAD

**Issue by viachaslauk** [OpenVPN/openvpn3#259]
Hi,

The windows client writes dns settings received by server to the registry  key `HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig`. Is there another way without writing this key?

**Comment by lstipakov** [comment]
Those are NRPT rules, which seem to be the most reliable way to set DNS. Also those are used for split-DNS functionality - when you need different DNS names to be resolved via different DNS servers. Anyway, do you experience any issues with this?

**Comment by viachaslauk** [comment]
In case after the system crash the client device can remain in a unmanageable state - if obtained DNS had restrict access . Or, if obtained DNS is public, then, after a crash, the client will continue to use them covertly even without a vpn connection, bypassing system settings from GUI/CLI. This may not be obvious to the average user.

**Comment by lstipakov** [comment]
Are you writing your own client based on openvpn3? You can obviously disable NRPT in code. We have so called separate agent process, which runs as a service, and does privileged operations such as setting up IP address, routing etc. if client process crashes, agent has fail-safe mechanism which got kicked in and revert all changes, including NRPT rules. I have to check the code, but in previous versions we also had fail-safe in agent - at startup it used to clean all OpenVPN - related keys. Lähetetty iPhonestaViachaslau Khalikin ***@***.***> kirjoitti 2.2.2023 kello 16.24:﻿
In case after the system crash the client device can remain in a unmanageable state - if obtained DNS had restrict access . Or, if obtained DNS is public, then, after a crash, the client will continue to use them covertly even without a vpn connection, bypassing system settings from GUI/CLI. This may not be obvious to the average user.

**Comment by viachaslauk** [comment]
> Are you writing your own client based on openvpn3? You can obviously disable NRPT in code. 

Yes,  i write own client based on [release/3.7.2](https://github.com/OpenVPN/openvpn3/releases/tag/release%2F3.7.2). I did not find this feature in the [top level interface](https://github.com/OpenVPN/openvpn3/blob/master/client/ovpncli.hpp). `allowLocalDnsResolvers` does not change this behavior. Only by explicitly changing  the `use_nrpt` value in  [tunsetup.hpp](https://github.com/OpenVPN/openvpn3/blob/master/openvpn/tun/win/client/tunsetup.hpp) made it possible to disable the NRPT rules.

> ... which runs as a service ...

Yes, I also came to this conclusion of the need to wrap in a system service. For example, with the `ovpncli` test utility from this repository, the described issue is reproduced by simply closing the command line window after connecting.
