### ISSUE TITLE
On Macos VPN is not passed to Android Emulator 

### ISSUE THREAD

**Issue by BetterB0y** [OpenVPN/openvpn3#260]
Up to now I used Tunnelblick on MacOS beacuse it passes VPN connection to Android Emulator from Android Studio.

I would love to use your software, but it's not passing my vpn connection. Can you fix that?

**Comment by schwabe** [comment]
This repository is not related to Tunnelblick or the OpenVPN implementation in Tunnelblick.

**Comment by BetterB0y** [comment]
@schwabe  I know. I'm asking about feature in OpenVPN Connect app

**Comment by schwabe** [comment]
Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.
