### ISSUE TITLE
Can dhcp-option PROXYAUTOURL parameter of OpenVPN be supported on Android and ios?

### ISSUE THREAD

**Issue by xiaotudoubaba** [OpenVPN/openvpn3#265]
The dhcp-option PROXYAUTOURL parameter is supported on Mac and Windows for OpenVPN on PC, but it does not work on the mobile platforms(android/ios).

**Comment by schwabe** [comment]
This is a question if the implementation of the clients on those platforms (e.g. Connect) supports it on those platforms.

Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.
