### ISSUE TITLE
why does resolve via google dns doesn't work with openvpn connect, but works with openvpn gui

### ISSUE THREAD

**Issue by emoxam** [OpenVPN/openvpn3#275]
Moved from openvpn gui to openvpn connect (3.3.7 (2979)), and on the same server with the same configon my windows 11 machine resolve doesn't work. But it working on the openvgui. But on the openvpn connect reslove doesn't work.What can i do ?

nslookup mail.emoxam.ru 8.8.8.8

```
    timeout was 2 seconds.
╤хЁтхЁ:  UnKnown
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
If i use OVPN server on Ubuntu - all works as expected.

**Comment by schwabe** [comment]
Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.
