### ISSUE TITLE
can't connect 

### ISSUE THREAD

**Issue by EricCai001** [OpenVPN/openvpn3#29]
The OpenVPN3 of the IOS client cannot connect to the OpenVPN server, which is the OpenVPN2.x version of the OpenVPN2.x client that sends connection requests. But the server prompts the message to be incorrect. I am not sure where the message appears, whether any configuration needs to be configured

**Comment by dsommers** [comment]
Such issues are better discussed in the support forums.  You'll find them here: https://openv.pn/supforums
