### ISSUE TITLE
How to build the library on windows?

### ISSUE THREAD

**Issue by k-kdan** [OpenVPN/openvpn3#291]
I followed the instructions here:

https://github.com/OpenVPN/openvpn3?tab=readme-ov-file#building-with-visual-studio

How should I go on from here? I do not see any lib files generated, where can I find them?

**Comment by schwabe** [comment]
There is no library target. OpenVPN3 library works by including the header files in your project and directly linking it. See the ovpncli test binary or one of the open source clients (ics-openvpn or openvpn3-linux).

**Comment by k-kdan** [comment]
I still can't manage to do this, can you help me out writing simple code to connect to an .ovpn file?

**Comment by dsommers** [comment]
@k-kdan Have a look at the reference client implementation: [test/ovpncli/cli.cpp](https://github.com/OpenVPN/openvpn3/blob/master/test/ovpncli/cli.cpp)
