### ISSUE TITLE
openvpn3 client for windows does GUI scaling very bad

### ISSUE THREAD

**Issue by rechterplank** [OpenVPN/openvpn3#294]
I use 150% scaling for my windows 10 desktop.

with this setting openvpn3 client GUI is way to large and at least twice the size of other applications, looks very ugly

**Comment by lstipakov** [comment]
What do you mean by "OpenVPN3 client GUI"?

**Comment by cron2** [comment]
I'd guess this is some sort of OpenVPN Connect issue...

... which means that it's in the wrong issue tracker, as this is only for OpenVPN 2.x (community edition).

Please report Connect issues to https://support.openvpn.net/
