### ISSUE TITLE
Server poll timeout

### ISSUE THREAD

**Issue by dancvrcek** [OpenVPN/openvpn3#3]
Possibly a bit out-of-scope but here we go. I was trying to find the code which defines behaviour of server polling as I'm getting timeouts when on a bad network, which makes the server unreachable for a few minutes.

**Comment by mattock** [comment]
Which OpenVPN version are you using? Which OS are you on?

**Comment by dancvrcek** [comment]
iOS, OpenVPN connect 1.1.1 build 212 

I understand it will use a different source code, but kind of hoping I can understand the behaviour and optimistically assume it can be applied.

**Comment by dsommers** [comment]
OpenVPN Connect is based upon this core library, so the code isn't too far away.

Regardless, still having this issue?  Places to start poking would probably be client/cliconnect.hpp
and client/cliopt.hpp.

**Comment by dsommers** [comment]
Closing this issue, as the details are scarce and this needs to be tested against the latest OpenVPN Connect.  If this is still an issue, feel free to reopen it with more details.

**Comment by dancvrcek** [comment]
Thanks David. There were two issues a) iOS app has its own settings, which override the config file - I didn't realize it at first (pretty annoying, if you want to automatically deploy changes) b) once we realized that, we were able to tweak the config so ti worked fairly reliably.
