### ISSUE TITLE
sha256sum not found on Mac

### ISSUE THREAD

**Issue by gayu-mike** [OpenVPN/openvpn3#30]
When I run `OSX_ONLY=1 /Users/zhengxinyu/src/ovpn3/core/scripts/mac/build-all` on my mac, I get `sha256sum not found`. Maybe it should be `shasum` instead of `sha256sum` in `function.sh`, but I'm not sure.

**Comment by ordex** [comment]
thanks for reporting this.
We have recently improved the build system, but some macOS might lack some functionality.

I'll double check and let you know.

**Comment by ordex** [comment]
You're right. We need to substitute `sha256sum` with `shasum -a 256` which seems to be available on a wider range of OSes.

**Comment by ordex** [comment]
this has been fixes on master. Thanks for reporting!
