### ISSUE TITLE
Is there a server that supports IV_ACC?

### ISSUE THREAD

**Issue by savely-krasovsky** [OpenVPN/openvpn3#318]
Where we can find server which supports `ACC` control channel command? As far as I see OpenVPN 3.9 already supports it, but OpenVPN master branch (which will probably be the base for the coming 2.7) still doesn't have any mention about it. Are you planning to release server support for openvpn 2.x at some point?

**Comment by schwabe** [comment]
There is a WIP commit in my repository. It is done when it is done.

**Comment by savely-krasovsky** [comment]
@schwabe sure! I am not pushing, just a question. Thanks! Will wait.

**Comment by savely-krasovsky** [comment]
Just if someone want to test: https://github.com/schwabe/openvpn/commit/6b6d220470a25483e1ea7cd01f8b9f7a8c01a216
