### ISSUE TITLE
TLS Error: TLS handshake failed

### ISSUE THREAD

**Issue by RanchenY** [OpenVPN/openvpn3#32]
Hi, 

I can't connect to the server, and the server tip:

`Tue Jan 16 10:12:41 2018 10.12.96.230 TLS: Initial packet from [AF_INET6]::ffff:10.12.96.230:63260, sid=1791af9f 87496712`
`Tue Jan 16 10:12:41 2018 10.12.96.230 TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.`
`Tue Jan 16 10:12:41 2018 10.12.96.230 OpenSSL: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher`
`Tue Jan 16 10:12:41 2018 10.12.96.230 TLS_ERROR: BIO read tls_read_plaintext error`
`Tue Jan 16 10:12:41 2018 10.12.96.230 TLS Error: TLS object -> incoming plaintext read error`
`Tue Jan 16 10:12:41 2018 10.12.96.230 TLS Error: TLS handshake failed`
`Tue Jan 16 10:12:41 2018 10.12.96.230 SIGUSR1[soft,tls-error] received, client-instance restarting`

thank you.

**Comment by ordex** [comment]
This is a bug tracker, not a support forum. Please write to the appropriate mailing list: https://sourceforge.net/p/openvpn/mailman/
