### ISSUE TITLE
"Shortcut Minimize" weird on Windows

### ISSUE THREAD

**Issue by gfody** [OpenVPN/openvpn3#333]
OpenVPN Connect has this option:
> ### Shortcut Minimize
> When VPN connection is launched from a
> shortcut, and no user input is required to
> authenticate connection, minimize the
> shortcut

..when enabled on Windows this causes the main window to be minimized to the taskbar after connecting. it's weird since there is already a tray icon (and closing exhibits "minimize to tray" behavior) we would normally close the window after connecting. so enabling this option creates a tiny bother of having to restore the window to close it (or a penalty click from a setting that seems like it was meant to save a click!)

**Comment by dsommers** [comment]
Please open a support ticket here: https://support.openvpn.com/hc/en-us/requests/new

OpenVPN Connect issues are not handled in the OpenVPN 3 Core Library project.
