### ISSUE TITLE
Cannot build on OSX

### ISSUE THREAD

**Issue by amhed** [OpenVPN/openvpn3#4]
Attempting to build the CLI on OSX and getting lots of errors related to namespace resolution: 
```
error: use of undeclared identifier 'openvpn_io'; did you mean 'openvpn'?
error: no member named 'mutable_buffer' in namespace 'openvpn'
```

**Comment by jamesyonan** [comment]
Asio is now an optional component, try running the build script with env var ASIO=1 to enable Asio inclusion.

**Comment by amhed** [comment]
There's something wrong with my OSX environment. Decided to create a virtual machine and build/use on linux. Thanks!

**Comment by mexsss** [comment]
If you still have the same issues while using `ASIO_DIR=~/src/mac/`, try `ASIO_DIR=~/src/mac/asio` - works for me.
