### ISSUE TITLE
Can't implement by OpenVPN3 to OpenVPN 2.x server?

### ISSUE THREAD

**Issue by laskdjlaskdj12** [OpenVPN/openvpn3#42]
Written By Read.me says that about 2017, can't functionally binding 2.x Server.
 than how about now?

**Comment by dsommers** [comment]
The OpenVPN 3 Core Library (this project) implements the core components for server and client operations.  But it does not carry any reference implementation for an OpenVPN 3 based server.  The whole session management code is missing in this regards.

But OpenVPN 3 is wire compatible with servers based on OpenVPN 2.3, as long as it does not reqiure some of the more exotic options.  To get an idea of what is supported by OpenVPN 3, have a look at the option parser for the [openvpn2](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/ovpn3cli/openvpn2#L207) wrapper in the the [openvpn3-linux](https://github.com/OpenVPN/openvpn3-linux/) project.  This list is not a complete list yet, but cover most of the option.  Options not found in this code is most likely not supported.

The README.md file will be updated accordingly to the current state.  So there is no need to open tickets like this to check if the README is up-to-date.
