### ISSUE TITLE
Windows VPN Provider integration

### ISSUE THREAD

**Issue by KreativJos** [OpenVPN/openvpn3#46]
Hi!
Is it possible to integrate the OpenVPN client into the Windows 10 VPN gui?
I am guessing this should be doable via creating a VPN provider application or sorts, like in [this app in the store](https://www.microsoft.com/nl-nl/store/p/pulse-secure/9nblggh3b0bp?cid=msft_web_search):
https://store-images.s-microsoft.com/image/apps.53834.13510798884282278.9a3fd515-63d0-4cc1-8f02-c7651438595a.5cd3468d-1015-4b11-be1c-c236c76c1cb5?w=1399&h=1375&q=60

**Comment by dsommers** [comment]
Yes, we're working on it.  It is moving slowly forward as we're ironing out some bugs with Microsoft in their VPN API.  We are currently targeting a new OpenVPN Connect client for Windows 10.

Closing this issue as it isn't strictly an OpenVPN 3 Core library specific issue.
