### ISSUE TITLE
Whether to support OpenVPNServiceInteractive connection?

### ISSUE THREAD

**Issue by wuanlee** [OpenVPN/openvpn3#47]
Does it support connection through OpenVPNServiceInteractive? If you support it would be great. thank you very much!

**Comment by mattock** [comment]
There is no support for OpenVPNServiceInteractive in OpenVPN 3. I believe the client using the Windows VPN API can be launched without admin privileges - is that correct @lstipakov ?

**Comment by wuanlee** [comment]
Ah okay. Yes, that would be really great!  
How to using the Windows VPN API ? 
@lstipakov Can you provide a simple example? Thank you for your help.

**Comment by mattock** [comment]
@wuanlee I can tell you there is no simple example. Microsoft is still ironing out bugs in their VPN API, so it is beta-level at best.

**Comment by wuanlee** [comment]
@mattock     The only practical way to do this on Windows 10 is based on OpenVPNServiceInteractive. I have passed the test on Windows10(OpenVPN2.4+). At this stage, if OpenVPN3 can support OpenVPNServiceInteractive, it is very convenient, you can easily and quickly connect to the VPN, because Windows's own VPN is really too inconvenient. Subsequent Windows systems will not allow any programs with administrator privileges to run on the platform. Can you publish an API that supports the OpenVPNServiceInteractive interface?

**Comment by dsommers** [comment]
OpenVPNServiceInteractive is a OpenVPN 2.x specific implementation. This will be handled differently in the Windows implementation of an OpenVPN 3 based client, because the code is completely different and allows a much tighter OS integration than OpenVPN 2.x. As @mattock says, we are also working on a specific Windows 10 client which facilitate a brand new VPN API in Windows.

**Comment by wuanlee** [comment]
@dsommers Very much looking forward to your good news. At present, it mainly solves two core problems: the first is the virtual drive problem (tap-windows6 or develop base on windows.networking.vpn, ),and the second is the routing problem. Even more troublesome is the Windows 10 S (released in 2019) and will not support the exe model. So basically it is necessary to subvert the entire ecology of the Windows operating system. This is an opportunity for everyone.It is estimated when your API can be released and whether there is a temporary solution? Thanks @mattock @dsommers

**Comment by dsommers** [comment]
We are fully aware of the advantages. No, we do not have an ETA currently as we are working closely with Microsoft ironing out some issues with the Windows VPN API. Until these fixes materializes in updated Windows versions, there is not much point at planning any OpenVPN Connect release utilizing this VPN API. It will come when Microsoft and we are ready and sure we have a working product.

Closing this now, as this is not strictly related to the OpenVPN 3 Core Library (this project), but related to a client implementation using this library.
