### ISSUE TITLE
ProfileMerge with PKCS12 file

### ISSUE THREAD

**Issue by Herz3h** [OpenVPN/openvpn3#50]
Hello,

I have a configuration file which references a PKCS12 file like this : 

```
pkcs12 myfile.p12
remote-cert-tls server
```

And when I try to use profile merge to inline its content into a string variable with following code : 

```
ProfileMerge profileMerge(confPath.toStdString(),
                                                     "ovpn",
                                                     "",
                                                     ProfileMerge::FOLLOW_FULL,
                                                     ProfileParseLimits::MAX_LINE_SIZE,
                                                     ProfileParseLimits::MAX_PROFILE_SIZE);
if(profileMerge.status() != ProfileMerge::MERGE_SUCCESS)
    return false;

cout << profileMerge.profile_content() << endl;
```
It simply prints content of config file with same lines as above at the end : 

```
pkcs12 myfile.p12
remote-cert-tls server
```

Is this normal behaviour ?

Thanks.

**Comment by dsommers** [comment]
Yes, most likely.  Are you compiling against mbed TLS or OpenSSL?  mbed TLS does not support PKCS#12 at all.  And I'm a bit uncertain whether the PKCS#12 support with OpenSSL has been fully implemented.

**Comment by Herz3h** [comment]
I compile against mbedTLS (followed instructions on main page)

**Comment by dsommers** [comment]
Okay, then this is completely expected.  PKCS#12 is definitely not supported by mbed TLS.

**Comment by Herz3h** [comment]
Just for info, I have tried with OpenSSL on Mac and it doesn't parse the p12 file into an inline configuration just like mbedTLS.
