### ISSUE TITLE
android/build-all fails

### ISSUE THREAD

**Issue by huntergregal** [OpenVPN/openvpn3#56]
```
BUILDING
~/git/ovpn3/deps/tc-arm/bin/arm-linux-androideabi-gcc -I../include -DMBEDTLS_RELAXED_X509_DATE -D__LP32__ -D__ANDROID_API__=14 -march=armv7-a -mthumb -fomit-frame-pointer --sysroot=~/git/ovpn3/deps/tc-arm/sysroot -O3 -fPIC -c aes.c
~/git/ovpn3/deps/tc-arm/bin/arm-linux-androideabi-gcc: line 2: ~/git/ovpn3/deps/tc-arm/bin/../../../../llvm/prebuilt/linux-x86_64/bin/clang: No such file or directory

```

It appears the paths are messed up? (Note I changed /home/xxxx/ to ~/ just for this issue)

I also had to manually set my ANDROID_NDK_ROOT even after source the required files in var/

android/build-toolchains also fails with ln -s errors for `cc`, `cc1` etc unless I comment out all but the target arch in android/build-toolchains

**Comment by schwabe** [comment]
The build for Android is outdated and will probably removed in the future.

But you can check out my own app (http://GitHub.com/schwabe/ics-openvpn) how to build for Android in the meantime

**Comment by schwabe** [comment]
Running any VPN binary on Android is complicated and messy. You need a rooted phone and you also need to writing custom code to actually do the right thing in terms of routing/interface setup. The normal Linux setup mechansim will only screw up Android's routing and nothing will work anymore.

**Comment by scruel** [comment]
I already rooted my phone, and I know how to manipulate the routing tables for creating custom tun interface, along with the iptables, I also got other VPN binaries worked on my phone, such as wireguard, tailscaled, etc., but I don't know how to make OpenVPN work at the similar way. Android only provided one slot for using VPNs, which are really inconvenient, that's why I am looking for the other solutions for OpenVPN.

**Comment by huntergregal** [comment]
This is quite an old thread. But if I recall - i ended up modifying dropbear ssh to handle ssh tun adapters. 

It is true that, at least at that time, android had some pretty convoluted routing tables. But once that was sorted out - the tunnels worked out perfectly.
