### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by t0nic** [OpenVPN/openvpn3#58]
I could write the GUI for windows, give me a heads up and ill make a pull request.

**Comment by schwabe** [comment]
Having a nice ui is always welcome. For better coordination I would recommend to post to openvpn-devel mailing list.

Also this is a library so a UI should live in a separate repository that makes uses of this library. E.g. https://github.com/schwabe/ics-openvpn or https://github.com/openvpn/openvpn3-linux/ are both open source projects that use this library.

**Comment by dsommers** [comment]
What @schwabe says, makes a lot of sense.

But one crucial and important detail; make sure you have a good design on the security and privilege separation/escalation side. The OpenVPN 3 code base can more easily be split into more pieces doing more limited work, most not requiring much privileges at all. But feel free to reach out with your ideas and implementation details before starting to code it; we might capture some important details which can make your work easier.

**Comment by schwabe** [comment]
Closing this since it not an issue but a general discussion
