### ISSUE TITLE
Implementation of TunBuilderBase class functions

### ISSUE THREAD

**Issue by mbjelo** [OpenVPN/openvpn3#59]
Hi, where we can find real implementation of functions from TunBuilderBase class, in bace.hpp file we have functions without code in them? Thanks

**Comment by schwabe** [comment]
The tunbuilder is for things like Android and iOS. The implementation of the OpenVPN Connect clients is not open source. However you can have a look at ics-openvpn (https://github.com/schwabe/ics-openvpn/blob/master/main/src/ovpn3/java/de/blinkt/openvpn/core/OpenVPNThreadv3.java) but that is also a quite big project.
