### ISSUE TITLE
Getting error when building

### ISSUE THREAD

**Issue by itaims** [OpenVPN/openvpn3#61]
Hello, 
I am getting following errors when building OpenVPN library.

> c:\Temp\O3\core\win>set O3=C:\Temp\O3 && python buildep.py
> Traceback (most recent call last):
>   File "buildep.py", line 5, in <module>
>     from utils import *
>   File "c:\Temp\O3\core\win\utils.py", line 2, in <module>
>     import requests
> ImportError: No module named requests

**Comment by lstipakov** [comment]
Hi,

You need to install "requests" python library, see http://docs.python-requests.org/en/master/user/install/.

**Comment by itaims** [comment]
I installed requests in python. But now there is another issue with patch. 


>  *** ['git', 'apply', '--whitespace=nowarn', '--ignore-space-change', '--verbose'
> , 'C:\\Temp\\O3\\core\\deps\\mbedtls\\patches\\0002-Enable-allowing-unsupported-
> critical-extensions-in-r1.patch']
> error: git apply: bad git-diff - expected /dev/null on line 294
> Traceback (most recent call last):
>   File "buildep.py", line 141, in <module>
>     build_all(read_params())
>   File "buildep.py", line 135, in build_all
>     build_mbedtls(parms)
>   File "buildep.py", line 64, in build_mbedtls
>     call(["git", "apply", "--whitespace=nowarn", "--ignore-space-change", "--ver
> bose", patch_file], cwd=dist)
>   File "c:\Temp\O3\core\win\utils.py", line 217, in call
>     raise ValueError("command failed with status %r (expected %r)" % (ret, succe
> ed))

**Comment by lstipakov** [comment]
Which version of git you use? I believe this problem is fixed after 2.17: https://github.com/git-for-windows/git/issues/1489

Otherwise run `git config --global core.autocrlf false` and do checkout again.

**Comment by lstipakov** [comment]
This

> error: tests/data_files/test-ca-nc.crt: already exists in working directory

signals that your mbedtls directory is left in somewhat inconsistent state from previous failed patch attempt.

Could you do a clean checkout and try once again?

**Comment by lstipakov** [comment]
@itaims can you confirm that you managed to build a test client?

**Comment by itaims** [comment]
Yes, Thank you, I built it successfully.
