### ISSUE TITLE
fatal error: asio.hpp: No such file or directory

### ISSUE THREAD

**Issue by XXvevo** [OpenVPN/openvpn3#63]
If I try to compile `build-linux` it says
```
OpenVPNClientThread.java:203: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

and if I remove the `@Override` annotation from file, it says

```
In file included from /root/ovpn3/core/client/ovpncli.cpp:30:0:
/root/ovpn3/core/openvpn/io/io.hpp:28:20: fatal error: asio.hpp: No such file or directory
compilation terminated.
```

Java version:
```
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-3)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

Please fix this issue.

**Comment by schwabe** [comment]
Please do not double post issues.

You failed to build the dependency or install the dependencies (ASIO). This should be apparent from the error message and doing minimal googling for asio.hpp. There is a linux/build-all script.
