### ISSUE TITLE
CHACHA20-POLY1305

### ISSUE THREAD

**Issue by promindsd** [OpenVPN/openvpn3#68]
Hello there!
Is there any chance or plan to see CHACHA20-POLY1305 supported in openvpn3 both for control and data channels?
I compiled openvpn3 with mbedtls (which provides CHACHA20) but it seems this cipher is not recognized or used by openvpn3.
I see openvpn 2.5 now supports CHACHA20 and I wonder whether the same can be done in openvpn3 in the near future or, at least, how this can be implemented by modifying the current sources.

Thank you.

**Comment by schwabe** [comment]
Chacha20-poly1305 for control channel requires TLS 1.3 support, which means OpenSSL 1.1.1. That should work out of the box with current master. For data channel I have not checked wether chacha20-poly1305 works as AEAD cipher. Technically there is nothing that should prevent that. As always patches are welcome.

**Comment by what951006** [comment]
> Hello there!
> Is there any chance or plan to see CHACHA20-POLY1305 supported in openvpn3 both for control and data channels?
> I compiled openvpn3 with mbedtls (which provides CHACHA20) but it seems this cipher is not recognized or used by openvpn3.
> I see openvpn 2.5 now supports CHACHA20 and I wonder whether the same can be done in openvpn3 in the near future or, at least, how this can be implemented by modifying the current sources.
> 
> Thank you.

why do you need chch20-poly1305 ? more faster?

**Comment by dsommers** [comment]
As of commit a2e2bf626e59ef95ce5a118f21e249c9e7b73c2a (2020-02-18), the data channel supports CHACHA20-Poly1305.  And as @schwabe mentioned, OpenSSL 1.1.1 enables TLSv1.3 which adds this cipher to the control channel.

Closing this issue, as this has been resolved.
