### ISSUE TITLE
iOS client - Slow tunnel?

### ISSUE THREAD

**Issue by devstar1988** [OpenVPN/openvpn3#7]
Hello, Developer

I am using this module for making iOS openvpn client.
When I check speed through vpn, it was too slow.

I am not sure what's wrong.
Can you help me?

**Comment by jeroenleenarts** [comment]
@devstar1988 Any luck solving this? And what steps did you use to build iOS lib version of OpenVpn3?

**Comment by ChineseRoyalStar** [comment]
Any solution until now? The same question with you. @jeroenleenarts  @devstar1988

**Comment by ordex** [comment]
OpenVPN Connect for iOS is a commercial product and it's unrelated to the FOSS project on GitHub.
To report bugs, please check https://forums.openvpn.net/viewtopic.php?f=36&t=25650
