### ISSUE TITLE
Building under MSYS2 + MingW32

### ISSUE THREAD

**Issue by mifritscher** [OpenVPN/openvpn3#71]
Almost works (using `ECHO=1 PROF=win ASIO_DIR=~/asio MTLS_SYS=1 NOSSL=1 $O3/core/scripts/build proto`)

I only had to tweak the command line 
`g++ -fwhole-program -Wall -Wno-sign-compare -Wno-unused-parameter -DUSE_MBEDTLS -DUSE_ASIO -DASIO_STANDALONE -DASIO_NO_DEPRECATED -I/home/michaelfritscher/asio/asio/include -I/home/michaelfritscher/ovpn3/core proto.cpp -o proto -lmbedtls -lmbedx509 -lmbedcrypto`

a bit to

`g++ -fwhole-program -Wall -Wno-sign-compare -Wno-unused-parameter -DUSE_MBEDTLS -DUSE_ASIO -DASIO_STANDALONE -DASIO_NO_DEPRECATED -I/home/michaelfritscher/asio/asio/include -I/home/michaelfritscher/ovpn3/core proto.cpp -o proto -lmbedtls -lmbedx509 -lmbedcrypto -lws2_32 -lwsock32`

Where should the `-lws2_32 -lwsock32` go? to core/scripts/build?

**Comment by mifritscher** [comment]
The result: 
`
$ time ./proto
*** app bytes=73264464 net_bytes=130443698 data_bytes=416057047 prog=0000218047/0000218046 D=10600/700/12600/700 N=109/109 SH=17000/14900 HE=0/0

real    0m27,222s
user    0m0,000s
sys     0m0,015s
`

**Comment by schwabe** [comment]
I am not sure if we officially want to support msys as nobody of us uses it and see if it is working. 

But if you really wanted to add it to that build system adding a new arch under `vars` (vars-msys) would be the way to go and then edit the code that detect the platform to set it `msys` rather than whatever it currently comes up with (Linux?).

You can also try building it in the same that `CMakeLists.txt` build the unit tests and `test/ovpncli`. Maybe cmake has better defaults? 

This all from someone who hasn't worked with msys in years.

**Comment by mifritscher** [comment]
A
```
michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core
$ mkdir build_cmake

michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core
$ cd build_cmake/

michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core/build_cmake
$ cmake ..
```
prints lots of

> System is unknown to cmake, create:
> Platform/MINGW64_NT-6.1-7601 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> 

But seems to work - but the linker needs literally hours...

I'll dig into the vars-route soon.

**Comment by mifritscher** [comment]
A
```
michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core
$ mkdir build_cmake

michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core
$ cd build_cmake/

michaelfritscher@fritscher2-lapt MINGW64 ~/O3/core/build_cmake
$ cmake ..
```
prints lots of

> System is unknown to cmake, create:
> Platform/MINGW64_NT-6.1-7601 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> 

and the linker abborted (after several hours...) with several kilometers of errors like
CMakeFiles/coreUnitTests.dir/test_log.cpp.obj:test_log.cpp:(.text$_ZN7openvpn17ParseClientConfigC1ERKNS_10OptionListE[_ZN7openvpn17ParseClientConfigC1ERKNS_10OptionListE]+0x772): undefined reference to `std::allocator<char>::allocator()'
CMakeFiles/coreUnitTests.dir/test_log.cpp.obj:test_log.cpp:(.text$_ZN7openvpn17ParseClientConfigC1ERKNS_10OptionListE[_ZN7openvpn17ParseClientConfigC1ERKNS_10OptionListE]+0x792): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
CM
../../lib/libgtest.a(gtest-all.cc.obj):gtest-all.cc:(.rdata$_ZTVN7testing17TestEventListenerE[_ZTVN7testing17TestEventListenerE]+0x28): undefined reference to `__cxa_pure_virtual'
C:/msys64/mingw64/lib/libcrypto.a(bss_sock.o):(.text+0x323): undefined reference to `__imp_recv'
C:/msys64/mingw64/lib/libcrypto.a(bss_sock.o):(.text+0x356): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/lib/libcrypto.a(bss_sock.o):(.text+0x405): undefined reference to `__imp_WSAGetLastError'



I'll dig into the vars-route soon.

**Comment by Nrakron** [comment]
> Almost works (using `ECHO=1 PROF=win ASIO_DIR=~/asio MTLS_SYS=1 NOSSL=1 $O3/core/scripts/build proto`)
> 
> I only had to tweak the command line
> `g++ -fwhole-program -Wall -Wno-sign-compare -Wno-unused-parameter -DUSE_MBEDTLS -DUSE_ASIO -DASIO_STANDALONE -DASIO_NO_DEPRECATED -I/home/michaelfritscher/asio/asio/include -I/home/michaelfritscher/ovpn3/core proto.cpp -o proto -lmbedtls -lmbedx509 -lmbedcrypto`
> 
> a bit to
> 
> `g++ -fwhole-program -Wall -Wno-sign-compare -Wno-unused-parameter -DUSE_MBEDTLS -DUSE_ASIO -DASIO_STANDALONE -DASIO_NO_DEPRECATED -I/home/michaelfritscher/asio/asio/include -I/home/michaelfritscher/ovpn3/core proto.cpp -o proto -lmbedtls -lmbedx509 -lmbedcrypto -lws2_32 -lwsock32`
> 
> Where should the `-lws2_32 -lwsock32` go? to core/scripts/build?
