### ISSUE TITLE
does  ping-restart can work when ping get timeout ?

### ISSUE THREAD

**Issue by wsktree** [OpenVPN/openvpn3#80]
it seems, openvpn3 client side did not implement ping-restart.
From the code, it just stop the conneciton when timout, but did not  reconnect it
code is bellow:
    // Possibly send a keepalive message, and check for expiration
    // of session due to lack of received packets from peer.
    void keepalive_housekeeping()
    {
      const Time now = *now_;

      // check for keepalive timeouts
      if (now >= keepalive_xmit && primary)
	{
	  primary->send_keepalive();
	  update_last_sent();
	}
      if (now >= keepalive_expire)
	{
	  // no contact with peer, disconnect
	  stats->error(Error::KEEPALIVE_TIMEOUT);
	  disconnect(Error::KEEPALIVE_TIMEOUT);
	}
    }

**Comment by lstipakov** [comment]
The code you've posted is from a protocol implementation. Ping-restart is handled in upper layer - see clientconnect.hpp, class ClientConnect.
