### ISSUE TITLE
compile error for windows

### ISSUE THREAD

**Issue by wsktree** [OpenVPN/openvpn3#81]
I have follow the steps and successfully run the steps: 
> c:\Temp\O3>cd core\win
> c:\Temp\O3\core\win>set O3=C:\Temp\O3 && python buildep.py

Then I go to visual2017 for buil, I get bellow error:
1>mbedtls.lib(md.obj) : error LNK2001: 无法解析的外部符号 __imp_ferror
1>mbedtls.lib(bignum.obj) : error LNK2001: 无法解析的外部符号 __imp_fgets
1>mbedtls.lib(rsa.obj) : error LNK2001: 无法解析的外部符号 __imp_rand
1>C:\Temp\O3\core\win\x64\Release\cli.exe : fatal error LNK1120: 3 个无法解析的外部命令
1>已完成生成项目“ovpn3-core.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

can any one help me ?
thanks very much!

**Comment by lstipakov** [comment]
Hi,

Looks like problem with library runtime linkage. Can you try to build dependencies with static linkage?

`set STATIC=1&& set DEBUG=1&& python buildep.py`

**Comment by wsktree** [comment]
issue resloved by  add "#pragma comment(lib,"msvcrtd.lib")"
in cli.cpp
