### ISSUE TITLE
reconnect make the tun device disappear some seconds

### ISSUE THREAD

**Issue by wsktree** [OpenVPN/openvpn3#83]
I am developing a openvpn client using the API on windows platform.
Now I face an issue when I call reconnect API the tun device disappear some seconds .
Is there API to just reconenct the network and do not disappear the tun device ,just keep it ?

I have  already add parameter "persist-tun".

BR.
wsktree

**Comment by schwabe** [comment]
You will notice that openvpn3 logs that it ignores that option. If you look closer at the client api, you will also notice that it has a method to set persistent-tun.
