### ISSUE TITLE
How to build for android

### ISSUE THREAD

**Issue by abdularis** [OpenVPN/openvpn3#87]
Hello, thanks before, this is a great project,
I have a little experience working with android native toolchain (I compiled some native android project before), but I still couldn't figure out how to build this project.
What android NDK version this project is using? I see read the build-android script and vars script for setting up the env variables for android build but it seems that the android ndk toolchain directory structure is quite different from what the official android NDK I downloaded.
Do I need to setting up ndk directory manually?
Best regards.

**Comment by schwabe** [comment]
See https://github.com/schwabe/ics-openvpn for a working open source build for this project.
