### ISSUE TITLE
Too many UI notifications

### ISSUE THREAD

**Issue by yuliyan-rhyme** [OpenVPN/openvpn3#89]
I'm using OpenVPN Connect ver 3.0.2.(598); Mac OS Mojave 10.14.6

Connection Timeout set to Continuously retry.

Once I "lock screen" and leave the machine for awhile, I've noticed that the machine continuously wake up the display and once I log in back, I see hundreds for UI notification messages "CONNECTED".

I assume the network is going down once I lock the screen and the Client doesn't notice that and tries to reconnect continuously (which is OK - I have specificed that option), however I don't see any reason why I see hundreds of notifications!? It is totaly ok to have one, or even none if the Client detects the "lock screen" mode.

Also if it is posslbe not to wake the display would be great.

The ideal solution would be that the Client is capable of detecting the Lock Screen and have an option NOT to display any notifications (presonally I don't need "CONNECTED" or anything like this messages). I guess not displaying any messages the problem with waking up the screen will vanish.

**Comment by novaflash** [comment]
Hello,

For the OpenVPN Connect commercial software you can report bugs on https://openvpn.net/support

Having said that, I have received information that this will be fixed in a future release of OpenVPN Connect v3. This issue is already known and will be fixed in a next release.

**Comment by dsommers** [comment]
Since this is an issue not related to the OpenVPN 3 Core Library (this project) but is an issue in the implementation of it (OpenVPN Connect), I'm closing this ticket.  This is not something we can handle in the Core library anyhow.
