### ISSUE TITLE
How can i get traffic with c++ library?

### ISSUE THREAD

**Issue by Tk4s** [OpenVPN/openvpn3#90]
Hi,
I have a problem that I want use code to get traffic. 
Can tell me which one func can do it?
=====
thx

**Comment by dsommers** [comment]
Lets first start with the basics.
Read this one first: [Ask smart questions - Before you ask](http://catb.org/~esr/faqs/smart-questions.html#before)
And then continue with this one: [Ask smart questions - When you ask](http://catb.org/~esr/faqs/smart-questions.html#asking) (the complete section, yeah I know it is fairly long and comprehensive).

Once you've figured out that, then feel free to come back and ask your question in a smarter way.
