### ISSUE TITLE
Installer failure: Unable to install driver

### ISSUE THREAD

**Issue by alexey-krylov** [OpenVPN/openvpn3#98]
Steps:
- Download installer
- Try to install

Expected behavior:
- Succeeded installation

Actual behavior:
- Automatic rollback of installation

Environment:
- OS: Win10, x64, version 1909
- Version: OpenVPN Connect, 3.1.1.378_signed.msi

Log data:

`MSI (s) (FC:6C) [09:47:31:987]: Executing op: FileCopy(SourceName=splhhbk9.sys|tap_ovpnconnect.sys,SourceCabKey=TapDriverSYSWin7_x86,DestName=tap_ovpnconnect.sys,Attributes=512,FileSize=»MSI (s) (FC:6C) [09:47:31:988]: File: C:\Program Files\OpenVPN Connect\drivers\tap\x86\win7\tap_ovpnconnect.sys;        To be installed;        Won't patch;    No existing file           MSI (s) (FC:6C) [09:47:31:988]: Source for file 'TapDriverSYSWin7_x86' is compressed                                                                                                       InstallFiles: File: tap_ovpnconnect.sys,  Directory: C:\Program Files\OpenVPN Connect\drivers\tap\x86\win7\,  Size: 25600                                                                  MSI (s) (FC:6C) [09:47:31:990]: Executing op: CacheSizeFlush(,)                                                                                                                            MSI (s) (FC:6C) [09:47:31:990]: Executing op: ActionStart(Name=InstallDriver_CA,,)                                                                                                         Action 9:47:31: InstallDriver_CA.                                                                                                                                                          MSI (s) (FC:6C) [09:47:31:995]: Executing op: CustomActionSchedule(Action=InstallDriver_CA,ActionType=3073,Source=BinaryData,Target=InstallDriver_CA,CustomActionData=C:\Program Files\Ope»MSI (s) (FC:00) [09:47:31:997]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIEE0B.tmp, Entrypoint: InstallDriver_CA                                                         MSI (s) (FC:CC) [09:47:31:997]: Generating random cookie.                                                                                                                                  MSI (s) (FC:CC) [09:47:32:001]: Created Custom Action Server with PID 4940 (0x134C).                                                                                                       MSI (s) (FC:DC) [09:47:32:020]: Running as a service.                                                                                                                                      MSI (s) (FC:DC) [09:47:32:024]: Hello, I'm your 64bit Elevated Non-remapped custom action server.                                                                                          get_win_version Enter                                                                                                                                                                      Command: wmic os get Caption /value                                                                                                                                                        CustomAction InstallDriver_CA returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)                                                  Action ended 9:47:32: InstallFinalize. Return value 3.                                                                                                                                     MSI (s) (FC:6C) [09:47:32:441]: Note: 1: 2265 2:  3: -2147287035                                                                                                                           MSI (s) (FC:6C) [09:47:32:442]: User policy value 'DisableRollback' is 0                                                                                                                   MSI (s) (FC:6C) [09:47:32:442]: Machine policy value 'DisableRollback' is 0                                                                                                                MSI (s) (FC:6C) [09:47:32:444]: Note: 1: 2318 2:                                                                                                                                           MSI (s) (FC:6C) [09:47:32:445]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1345211888,LangId=1033,Platform=589824,ScriptType=2,Scri`

Log attached
[install.txt](https://github.com/OpenVPN/openvpn3/files/4058144/install.txt)

After 3.1.1 failed installation i've successfully installed version 2.4.8.

**Comment by alexey-krylov** [comment]
Probably it's related to this:
https://forums.openvpn.net/viewtopic.php?f=29&t=29285

Log collected with command:
msiexec /i openvpn-connect-3.1.1.378_signed.msi /L*v install.txt

**Comment by lstipakov** [comment]
Hi,

This is not openvpn connect support channel, please use https://openvpn.net/support

**Comment by alexey-krylov** [comment]
Okay, will try to post there. Thanks
